// @ts-nocheck

import type { Monaco } from "@monaco-editor/react";
import { DiffEditor, loader } from "@monaco-editor/react";
import { wireTmGrammars } from "monaco-editor-textmate";
import { Registry } from "monaco-textmate";
import { newCode, oldCode } from "./test-code1";

// const vesperThemeColors = {
//   "activityBar.activeBorder": "#e6b450",
//   "activityBar.background": "#0d1017",
//   "activityBar.border": "#1b1f29",
//   "activityBar.foreground": "#555e73cc",
//   "activityBar.inactiveForeground": "#555e7399",
//   "activityBarBadge.background": "#e6b450",
//   "activityBarBadge.foreground": "#805600",
//   "activityBarTop.activeBorder": "#e6b450",
//   "activityBarTop.foreground": "#646c7f",
//   "badge.background": "#e6b45033",
//   "badge.foreground": "#e6b450",
//   "button.background": "#e6b450",
//   "button.border": "#8056001a",
//   "button.foreground": "#805600",
//   "button.hoverBackground": "#deae4d",
//   "button.secondaryBackground": "#555e7333",
//   "button.secondaryForeground": "#bfbdb6",
//   "button.secondaryHoverBackground": "#555e7380",
//   "button.separator": "#8056004d",
//   "chat.checkpointSeparator": "#99adbf8c",
//   "chat.editedFileForeground": "#73b8ff",
//   "chat.requestBackground": "#0d1017",
//   "chat.requestBorder": "#47526640",
//   "chat.requestBubbleBackground": "#47526633",
//   "chat.requestBubbleHoverBackground": "#47526640",
//   "chat.slashCommandBackground": "#39bae633",
//   "chat.slashCommandForeground": "#39bae6",
//   "commandCenter.activeBackground": "#47526640",
//   "commandCenter.activeBorder": "#47526600",
//   "commandCenter.activeForeground": "#555e73",
//   "commandCenter.background": "#10141c",
//   "commandCenter.border": "#1b1f29",
//   "commandCenter.foreground": "#555e73",
//   "commandCenter.inactiveBorder": "#1b1f29",
//   "debugConsoleInputIcon.foreground": "#e6b450",
//   "debugExceptionWidget.background": "#141821",
//   "debugExceptionWidget.border": "#1b1f29",
//   "debugIcon.breakpointDisabledForeground": "#f2966880",
//   "debugIcon.breakpointForeground": "#f29668",
//   "debugToolBar.background": "#141821",
//   descriptionForeground: "#555e73",
//   "diffEditor.diagonalFill": "#1b1f29",
//   "diffEditor.insertedTextBackground": "#70bf561f",
//   "diffEditor.removedTextBackground": "#f26d781f",
//   "dropdown.background": "#141821",
//   "dropdown.border": "#1b1f29",
//   "dropdown.foreground": "#555e73",
//   "editor.background": "#0A0A0A",
//   "editor.findMatchBackground": "#4c4126",
//   "editor.findMatchHighlightBackground": "#4c412680",
//   "editor.foreground": "#bfbdb6",
//   "editor.inactiveSelectionBackground": "#80b5ff26",
//   "editor.lineHighlightBackground": "#161a24",
//   "editor.rangeHighlightBackground": "#4c412633",
//   "editor.selectionBackground": "#3388ff40",
//   "editor.selectionHighlightBackground": "#70bf5626",
//   "editor.selectionHighlightBorder": "#70bf5600",
//   "editor.snippetTabstopHighlightBackground": "#70bf5633",
//   "editor.wordHighlightBackground": "#73b8ff14",
//   "editor.wordHighlightBorder": "#73b8ff80",
//   "editor.wordHighlightStrongBackground": "#70bf5614",
//   "editor.wordHighlightStrongBorder": "#70bf5680",
//   "editorBracketMatch.background": "#6c73804d",
//   "editorBracketMatch.border": "#6c73804d",
//   "editorCodeLens.foreground": "#99adbf8c",
//   "editorCursor.foreground": "#e6b450",
//   "editorError.foreground": "#d95757",
//   "editorGroup.border": "#1b1f29",
//   "editorGroupHeader.noTabsBackground": "#0d1017",
//   "editorGroupHeader.tabsBackground": "#0d1017",
//   "editorGroupHeader.tabsBorder": "#1b1f29",
//   "editorGutter.addedBackground": "#70bf56",
//   "editorGutter.deletedBackground": "#f26d78",
//   "editorGutter.modifiedBackground": "#73b8ff",
//   "editorHoverWidget.background": "#141821",
//   "editorHoverWidget.border": "#1b1f29",
//   "editorInlayHint.foreground": "#bfbdb680",
//   "editorLineNumber.activeForeground": "#6c7380e6",
//   "editorLineNumber.foreground": "#6c738099",
//   "editorLink.activeForeground": "#e6b450",
//   "editorMarkerNavigation.background": "#141821",
//   "editorOverviewRuler.addedForeground": "#70bf56",
//   "editorOverviewRuler.border": "#1b1f29",
//   "editorOverviewRuler.bracketMatchForeground": "#6c7380b3",
//   "editorOverviewRuler.deletedForeground": "#f26d78",
//   "editorOverviewRuler.errorForeground": "#d95757",
//   "editorOverviewRuler.findMatchForeground": "#4c4126",
//   "editorOverviewRuler.modifiedForeground": "#73b8ff",
//   "editorOverviewRuler.warningForeground": "#e6b450",
//   "editorOverviewRuler.wordHighlightForeground": "#73b8ff66",
//   "editorOverviewRuler.wordHighlightStrongForeground": "#70bf5666",
//   "editorRuler.foreground": "#6c738033",
//   "editorStickyScroll.border": "#1b1f29",
//   "editorStickyScroll.shadow": "#00000080",
//   "editorStickyScrollHover.background": "#47526633",
//   "editorSuggestWidget.background": "#141821",
//   "editorSuggestWidget.border": "#1b1f29",
//   "editorSuggestWidget.highlightForeground": "#e6b450",
//   "editorSuggestWidget.selectedBackground": "#47526640",
//   "editorWarning.foreground": "#e6b450",
//   "editorWhitespace.foreground": "#6c738099",
//   "editorWidget.background": "#141821",
//   "editorWidget.border": "#1b1f29",
//   "editorWidget.resizeBorder": "#141821",
//   errorForeground: "#d95757",
//   "extensionButton.prominentBackground": "#e6b450",
//   "extensionButton.prominentForeground": "#805600",
//   "extensionButton.prominentHoverBackground": "#e2b14f",
//   focusBorder: "#e6b450",
//   foreground: "#555e73",
//   "gitDecoration.conflictingResourceForeground": "#ff0000",
//   "gitDecoration.deletedResourceForeground": "#f26d78",
//   "gitDecoration.ignoredResourceForeground": "#555e7380",
//   "gitDecoration.modifiedResourceForeground": "#73b8ff",
//   "gitDecoration.submoduleResourceForeground": "#d2a6ff",
//   "gitDecoration.untrackedResourceForeground": "#70bf56",
//   "icon.foreground": "#555e73",
//   "inlineChat.background": "#141821",
//   "inlineChat.border": "#1b1f29",
//   "inlineChat.foreground": "#bfbdb6",
//   "inlineChat.shadow": "#00000080",
//   "inlineChatDiff.inserted": "#70bf5633",
//   "inlineChatDiff.removed": "#f26d7833",
//   "inlineChatInput.background": "#10141c",
//   "inlineChatInput.border": "#1b1f29",
//   "inlineChatInput.focusBorder": "#e6b450b3",
//   "inlineChatInput.placeholderForeground": "#555e7380",
//   "inlineEdit.gutterIndicator.background": "#1b1f29",
//   "inlineEdit.gutterIndicator.primaryBackground": "#e6b4501a",
//   "inlineEdit.gutterIndicator.primaryBorder": "#e6b450",
//   "inlineEdit.gutterIndicator.primaryForeground": "#e6b450",
//   "inlineEdit.gutterIndicator.secondaryBackground": "#555e731a",
//   "inlineEdit.gutterIndicator.secondaryBorder": "#555e7380",
//   "inlineEdit.gutterIndicator.secondaryForeground": "#555e73",
//   "inlineEdit.gutterIndicator.successfulBackground": "#70bf561a",
//   "inlineEdit.gutterIndicator.successfulBorder": "#70bf56",
//   "inlineEdit.gutterIndicator.successfulForeground": "#70bf56",
//   "inlineEdit.modifiedBackground": "#70bf561a",
//   "inlineEdit.modifiedBorder": "#70bf5680",
//   "inlineEdit.modifiedChangedLineBackground": "#70bf5626",
//   "inlineEdit.modifiedChangedTextBackground": "#70bf5640",
//   "inlineEdit.originalBackground": "#f26d781a",
//   "inlineEdit.originalBorder": "#f26d7880",
//   "inlineEdit.originalChangedLineBackground": "#f26d7826",
//   "inlineEdit.originalChangedTextBackground": "#f26d7840",
//   "input.background": "#10141c",
//   "input.border": "#555e7333",
//   "input.foreground": "#bfbdb6",
//   "input.placeholderForeground": "#555e7380",
//   "inputOption.activeBackground": "#e6b4501a",
//   "inputOption.activeBorder": "#e6b45033",
//   "inputOption.activeForeground": "#e6b450",
//   "inputOption.hoverBackground": "#555e7333",
//   "inputValidation.errorBackground": "#10141c",
//   "inputValidation.errorBorder": "#d95757",
//   "inputValidation.infoBackground": "#0d1017",
//   "inputValidation.infoBorder": "#39bae6",
//   "inputValidation.warningBackground": "#0d1017",
//   "inputValidation.warningBorder": "#ffb454",
//   "keybindingLabel.background": "#555e731a",
//   "keybindingLabel.border": "#bfbdb61a",
//   "keybindingLabel.bottomBorder": "#bfbdb61a",
//   "keybindingLabel.foreground": "#bfbdb6",
//   "list.activeSelectionBackground": "#47526640",
//   "list.activeSelectionForeground": "#bfbdb6",
//   "list.deemphasizedForeground": "#d95757",
//   "list.errorForeground": "#d95757",
//   "list.filterMatchBackground": "#43392180",
//   "list.filterMatchBorder": "#4c412680",
//   "list.focusBackground": "#47526640",
//   "list.focusForeground": "#bfbdb6",
//   "list.focusOutline": "#47526640",
//   "list.highlightForeground": "#e6b450",
//   "list.hoverBackground": "#47526640",
//   "list.inactiveSelectionBackground": "#47526633",
//   "list.inactiveSelectionForeground": "#555e73",
//   "list.invalidItemForeground": "#555e734d",
//   "listFilterWidget.background": "#141821",
//   "listFilterWidget.noMatchesOutline": "#d95757",
//   "listFilterWidget.outline": "#e6b450",
//   "minimap.background": "#10141c",
//   "minimap.errorHighlight": "#d95757",
//   "minimap.findMatchHighlight": "#4c4126",
//   "minimap.selectionHighlight": "#3388ff40",
//   "minimapGutter.addedBackground": "#70bf56",
//   "minimapGutter.deletedBackground": "#f26d78",
//   "minimapGutter.modifiedBackground": "#73b8ff",
//   "multiDiffEditor.background": "#0d1017",
//   "multiDiffEditor.border": "#1b1f29",
//   "multiDiffEditor.headerBackground": "#141821",
//   "panel.background": "#0d1017",
//   "panel.border": "#1b1f29",
//   "panelStickyScroll.border": "#1b1f29",
//   "panelStickyScroll.shadow": "#00000080",
//   "panelTitle.activeBorder": "#e6b450",
//   "panelTitle.activeForeground": "#bfbdb6",
//   "panelTitle.inactiveForeground": "#555e73",
//   "peekView.border": "#47526640",
//   "peekViewEditor.background": "#141821",
//   "peekViewEditor.matchHighlightBackground": "#4c412680",
//   "peekViewEditor.matchHighlightBorder": "#43392180",
//   "peekViewResult.background": "#141821",
//   "peekViewResult.fileForeground": "#bfbdb6",
//   "peekViewResult.lineForeground": "#555e73",
//   "peekViewResult.matchHighlightBackground": "#4c412680",
//   "peekViewResult.selectionBackground": "#47526640",
//   "peekViewTitle.background": "#47526640",
//   "peekViewTitleDescription.foreground": "#555e73",
//   "peekViewTitleLabel.foreground": "#bfbdb6",
//   "pickerGroup.border": "#1b1f29",
//   "pickerGroup.foreground": "#555e7380",
//   "profileBadge.background": "#e6b450",
//   "profileBadge.foreground": "#805600",
//   "progressBar.background": "#e6b450",
//   "scrollbar.shadow": "#1b1f2900",
//   "scrollbarSlider.activeBackground": "#555e73b3",
//   "scrollbarSlider.background": "#555e7366",
//   "scrollbarSlider.hoverBackground": "#555e7399",
//   "selection.background": "#3388ff40",
//   "settings.headerForeground": "#bfbdb6",
//   "settings.modifiedItemIndicator": "#73b8ff",
//   "sideBar.background": "#0d1017",
//   "sideBar.border": "#1b1f29",
//   "sideBarSectionHeader.background": "#0d1017",
//   "sideBarSectionHeader.border": "#1b1f29",
//   "sideBarSectionHeader.foreground": "#555e73",
//   "sideBarStickyScroll.border": "#1b1f29",
//   "sideBarStickyScroll.shadow": "#00000080",
//   "sideBarTitle.foreground": "#555e73",
//   "statusBar.background": "#0d1017",
//   "statusBar.border": "#1b1f29",
//   "statusBar.debuggingBackground": "#f29668",
//   "statusBar.debuggingForeground": "#10141c",
//   "statusBar.foreground": "#555e73",
//   "statusBar.noFolderBackground": "#141821",
//   "statusBarItem.activeBackground": "#555e7333",
//   "statusBarItem.hoverBackground": "#555e7333",
//   "statusBarItem.prominentBackground": "#1b1f29",
//   "statusBarItem.prominentHoverBackground": "#00000030",
//   "statusBarItem.remoteBackground": "#e6b450",
//   "statusBarItem.remoteForeground": "#805600",
//   "symbolIcon.arrayForeground": "#59c2ff",
//   "symbolIcon.booleanForeground": "#d2a6ff",
//   "symbolIcon.classForeground": "#59c2ff",
//   "symbolIcon.colorForeground": "#e6c08a",
//   "symbolIcon.constantForeground": "#d2a6ff",
//   "symbolIcon.constructorForeground": "#ffb454",
//   "symbolIcon.enumeratorForeground": "#59c2ff",
//   "symbolIcon.enumeratorMemberForeground": "#d2a6ff",
//   "symbolIcon.eventForeground": "#e6c08a",
//   "symbolIcon.fieldForeground": "#f07178",
//   "symbolIcon.fileForeground": "#555e73",
//   "symbolIcon.folderForeground": "#555e73",
//   "symbolIcon.functionForeground": "#ffb454",
//   "symbolIcon.interfaceForeground": "#59c2ff",
//   "symbolIcon.keyForeground": "#39bae6",
//   "symbolIcon.keywordForeground": "#ff8f40",
//   "symbolIcon.methodForeground": "#ffb454",
//   "symbolIcon.moduleForeground": "#aad94c",
//   "symbolIcon.namespaceForeground": "#aad94c",
//   "symbolIcon.nullForeground": "#d2a6ff",
//   "symbolIcon.numberForeground": "#d2a6ff",
//   "symbolIcon.objectForeground": "#59c2ff",
//   "symbolIcon.operatorForeground": "#f29668",
//   "symbolIcon.packageForeground": "#aad94c",
//   "symbolIcon.propertyForeground": "#f07178",
//   "symbolIcon.referenceForeground": "#59c2ff",
//   "symbolIcon.snippetForeground": "#e6c08a",
//   "symbolIcon.stringForeground": "#aad94c",
//   "symbolIcon.structForeground": "#59c2ff",
//   "symbolIcon.textForeground": "#bfbdb6",
//   "symbolIcon.typeParameterForeground": "#59c2ff",
//   "symbolIcon.unitForeground": "#d2a6ff",
//   "symbolIcon.variableForeground": "#bfbdb6",
//   "tab.activeBackground": "#10141c",
//   "tab.activeBorder": "#10141c",
//   "tab.activeBorderTop": "#e6b450",
//   "tab.activeForeground": "#bfbdb6",
//   "tab.border": "#1b1f29",
//   "tab.inactiveBackground": "#0d1017",
//   "tab.inactiveForeground": "#555e73",
//   "tab.unfocusedActiveBorderTop": "#555e73",
//   "tab.unfocusedActiveForeground": "#555e73",
//   "tab.unfocusedInactiveForeground": "#555e73",
//   "terminal.ansiBlack": "#1b1f29",
//   "terminal.ansiBlue": "#4fbfff",
//   "terminal.ansiBrightBlack": "#686868",
//   "terminal.ansiBrightBlue": "#59c2ff",
//   "terminal.ansiBrightCyan": "#95e6cb",
//   "terminal.ansiBrightGreen": "#aad94c",
//   "terminal.ansiBrightMagenta": "#d2a6ff",
//   "terminal.ansiBrightRed": "#f07178",
//   "terminal.ansiBrightWhite": "#ffffff",
//   "terminal.ansiBrightYellow": "#ffb454",
//   "terminal.ansiCyan": "#93e2c8",
//   "terminal.ansiGreen": "#70bf56",
//   "terminal.ansiMagenta": "#d0a1ff",
//   "terminal.ansiRed": "#f06b73",
//   "terminal.ansiWhite": "#c7c7c7",
//   "terminal.ansiYellow": "#fdb04c",
//   "terminal.background": "#0d1017",
//   "terminal.foreground": "#bfbdb6",
//   "terminalCommandGuide.foreground": "#555e734d",
//   "terminalStickyScroll.border": "#1b1f29",
//   "terminalStickyScrollHover.background": "#47526633",
//   "textBlockQuote.background": "#141821",
//   "textLink.activeForeground": "#e6b450",
//   "textLink.foreground": "#e6b450",
//   "textPreformat.foreground": "#bfbdb6",
//   "titleBar.activeBackground": "#0d1017",
//   "titleBar.activeForeground": "#555e73",
//   "titleBar.border": "#1b1f29",
//   "titleBar.inactiveBackground": "#0d1017",
//   "titleBar.inactiveForeground": "#555e73b3",
//   "toolbar.hoverBackground": "#555e734d",
//   "tree.indentGuidesStroke": "#6c738080",
//   "walkThrough.embeddedEditorBackground": "#141821",
//   "welcomePage.progress.background": "#161a24",
//   "welcomePage.tileBackground": "#0d1017",
//   "widget.border": "#1b1f29",
//   "widget.shadow": "#00000080",
// } as const;

const vesperThemeColors = {
  "activityBar.background": "#101010",
  "activityBar.foreground": "#a0a0a0",
  "activityBarBadge.background": "#ffc799",
  "activityBarBadge.foreground": "#000000",
  "badge.background": "#ffc799",
  "badge.foreground": "#000000",
  "button.background": "#ffc799",
  "button.foreground": "#000000",
  "button.hoverBackground": "#ffcfa8",
  "diffEditor.insertedLineBackground": "#99ffe415",
  "diffEditor.insertedTextBackground": "#99ffe415",
  "diffEditor.removedLineBackground": "#ff808015",
  "diffEditor.removedTextBackground": "#ff808015",
  "editor.background": "#0a0a0a",
  "editor.foreground": "#ffffff",
  "editor.lineHighlightBackground": "#33333360",
  "editor.lineHighlightBorder": "#33333310",
  "editor.selectionBackground": "#ffffff25",
  "editor.selectionHighlightBackground": "#ffffff25",
  "editorBracketHighlight.foreground1": "#a0a0a0",
  "editorBracketHighlight.foreground2": "#a0a0a0",
  "editorBracketHighlight.foreground3": "#a0a0a0",
  "editorBracketHighlight.foreground4": "#a0a0a0",
  "editorBracketHighlight.foreground5": "#a0a0a0",
  "editorBracketHighlight.foreground6": "#a0a0a0",
  "editorBracketHighlight.unexpectedBracket.foreground": "#ff8080",
  "editorError.foreground": "#ff8080",
  "editorGroupHeader.tabsBackground": "#101010",
  "editorGutter.addedBackground": "#99ffe4",
  "editorGutter.deletedBackground": "#ff8080",
  "editorGutter.modifiedBackground": "#ffc799",
  "editorHoverWidget.background": "#161616",
  "editorHoverWidget.border": "#282828",
  "editorInlayHint.background": "#1c1c1c",
  "editorInlayHint.foreground": "#a0a0a0",
  "editorLineNumber.foreground": "#505050",
  "editorOverviewRuler.border": "#101010",
  "editorWarning.foreground": "#ffc799",
  "editorWidget.background": "#101010",
  focusBorder: "#ffc799",
  "icon.foreground": "#a0a0a0",
  "input.background": "#1c1c1c",
  "list.activeSelectionBackground": "#232323",
  "list.activeSelectionForeground": "#ffc799",
  "list.errorForeground": "#ff8080",
  "list.highlightForeground": "#ffc799",
  "list.hoverBackground": "#282828",
  "list.inactiveSelectionBackground": "#232323",
  "scrollbarSlider.background": "#34343480",
  "scrollbarSlider.hoverBackground": "#343434",
  "selection.background": "#666666",
  "settings.modifiedItemIndicator": "#ffc799",
  "sideBar.background": "#101010",
  "sideBar.border": "#33333360",
  "sideBarSectionHeader.background": "#101010",
  "sideBarSectionHeader.foreground": "#a0a0a0",
  "sideBarTitle.foreground": "#a0a0a0",
  "statusBar.background": "#101010",
  "statusBar.border": "#33333360",
  "statusBar.debuggingBackground": "#ff7300",
  "statusBar.debuggingForeground": "#ffffff",
  "statusBar.foreground": "#a0a0a0",
  "statusBarItem.remoteBackground": "#ffc799",
  "statusBarItem.remoteForeground": "#000000",
  "tab.activeBackground": "#1e1e1e7e",
  "tab.activeBorder": "#ffffff50",
  "tab.border": "#33333360",
  "tab.hoverBorder": "#ffffff40",
  "tab.inactiveBackground": "#101010",
  "textLink.activeForeground": "#ffcfa8",
  "textLink.foreground": "#ffc799",
  "titleBar.activeBackground": "#101010",
  "titleBar.activeForeground": "#7e7e7e",
  "titleBar.border": "#33333380",
  "titleBar.inactiveBackground": "#101010",
  "titleBar.inactiveForeground": "#707070",
  "window.activeBorder": "#333333",
} as const;

const vesperTokenColors = [
  {
    scope: ["comment", "punctuation.definition.comment"],
    settings: {
      foreground: "#8B8B8B94",
    },
  },
  {
    scope: ["variable", "string constant.other.placeholder", "entity.name.tag"],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: ["constant.other.color"],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: ["invalid", "invalid.illegal"],
    settings: {
      foreground: "#FF8080",
    },
  },
  {
    scope: ["keyword", "storage.type", "storage.modifier"],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: [
      "keyword.control",
      "constant.other.color",
      "punctuation.definition.tag",
      "punctuation.separator.inheritance.php",
      "punctuation.definition.tag.html",
      "punctuation.definition.tag.begin.html",
      "punctuation.definition.tag.end.html",
      "punctuation.section.embedded",
      "keyword.other.template",
      "keyword.other.substitution",
    ],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: ["entity.name.tag", "meta.tag.sgml", "markup.deleted.git_gutter"],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "entity.name.function",
      "variable.function",
      "support.function",
      "keyword.other.special-method",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: ["meta.block variable.other"],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: ["support.other.variable", "string.other.link"],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: [
      "constant.numeric",
      "support.constant",
      "constant.character",
      "constant.escape",
      "keyword.other.unit",
      "keyword.other",
      "constant.language.boolean",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "string",
      "constant.other.symbol",
      "constant.other.key",
      "meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js",
    ],
    settings: {
      foreground: "#99FFE4",
    },
  },
  {
    scope: [
      "entity.name",
      "support.type",
      "support.class",
      "support.other.namespace.use.php",
      "meta.use.php",
      "support.other.namespace.php",
      "markup.changed.git_gutter",
      "support.type.sys-types",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "source.css support.type.property-name",
      "source.sass support.type.property-name",
      "source.scss support.type.property-name",
      "source.less support.type.property-name",
      "source.stylus support.type.property-name",
      "source.postcss support.type.property-name",
      "source.postcss support.type.property-name",
      "support.type.vendored.property-name.css",
      "source.css.scss entity.name.tag",
      "variable.parameter.keyframe-list.css",
      "meta.property-name.css",
      "variable.parameter.url.scss",
      "meta.property-value.scss",
      "meta.property-value.css",
    ],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: [
      "entity.name.module.js",
      "variable.import.parameter.js",
      "variable.other.class.js",
    ],
    settings: {
      foreground: "#FF8080",
    },
  },
  {
    scope: ["variable.language"],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: ["entity.name.method.js"],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: [
      "meta.class-method.js entity.name.function.js",
      "variable.function.constructor",
    ],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: [
      "entity.other.attribute-name",
      "meta.property-list.scss",
      "meta.attribute-selector.scss",
      "meta.property-value.css",
      "entity.other.keyframe-offset.css",
      "meta.selector.css",
      "entity.name.tag.reference.scss",
      "entity.name.tag.nesting.css",
      "punctuation.separator.key-value.css",
    ],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: [
      "text.html.basic entity.other.attribute-name.html",
      "text.html.basic entity.other.attribute-name",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "entity.other.attribute-name.class",
      "entity.other.attribute-name.id",
      "meta.attribute-selector.scss",
      "variable.parameter.misc.css",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: ["source.sass keyword.control", "meta.attribute-selector.scss"],
    settings: {
      foreground: "#99FFE4",
    },
  },
  {
    scope: ["markup.inserted"],
    settings: {
      foreground: "#99FFE4",
    },
  },
  {
    scope: ["markup.deleted"],
    settings: {
      foreground: "#FF8080",
    },
  },
  {
    scope: ["markup.changed"],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: ["string.regexp"],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: ["constant.character.escape"],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: ["*url*", "*link*", "*uri*"],
    settings: {
      fontStyle: "underline",
    },
  },
  {
    scope: [
      "tag.decorator.js entity.name.tag.js",
      "tag.decorator.js punctuation.definition.tag.js",
    ],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: ["source.js constant.other.object.key.js string.unquoted.label.js"],
    settings: {
      foreground: "#FF8080",
      fontStyle: "italic",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: ["text.html.markdown", "punctuation.definition.list_item.markdown"],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: ["text.html.markdown markup.inline.raw.markdown"],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: [
      "text.html.markdown markup.inline.raw.markdown punctuation.definition.raw.markdown",
    ],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: [
      "markdown.heading",
      "markup.heading | markup.heading entity.name",
      "markup.heading.markdown punctuation.definition.heading.markdown",
      "markup.heading",
      "markup.inserted.git_gutter",
    ],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: ["markup.italic"],
    settings: {
      foreground: "#FFFFFF",
      fontStyle: "italic",
    },
  },
  {
    scope: ["markup.bold", "markup.bold string"],
    settings: {
      foreground: "#FFFFFF",
      fontStyle: "bold",
    },
  },
  {
    scope: [
      "markup.bold markup.italic",
      "markup.italic markup.bold",
      "markup.quote markup.bold",
      "markup.bold markup.italic string",
      "markup.italic markup.bold string",
      "markup.quote markup.bold string",
    ],
    settings: {
      foreground: "#FFFFFF",
      fontStyle: "bold",
    },
  },
  {
    scope: ["markup.underline"],
    settings: {
      foreground: "#FFC799",
      fontStyle: "underline",
    },
  },
  {
    scope: ["markup.quote punctuation.definition.blockquote.markdown"],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: ["string.other.link.title.markdown"],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: ["string.other.link.description.title.markdown"],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: ["constant.other.reference.link.markdown"],
    settings: {
      foreground: "#FFC799",
    },
  },
  {
    scope: ["markup.raw.block"],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: ["markup.raw.block.fenced.markdown"],
    settings: {
      foreground: "#00000050",
    },
  },
  {
    scope: ["punctuation.definition.fenced.markdown"],
    settings: {
      foreground: "#00000050",
    },
  },
  {
    scope: [
      "markup.raw.block.fenced.markdown",
      "variable.language.fenced.markdown",
      "punctuation.section.class.end",
    ],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: ["variable.language.fenced.markdown"],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: ["meta.separator"],
    settings: {
      foreground: "#65737E",
      fontStyle: "bold",
    },
  },
  {
    scope: ["markup.table"],
    settings: {
      foreground: "#FFFFFF",
    },
  },
  {
    scope: "token.info-token",
    settings: {
      foreground: "#6796E6",
    },
  },
  {
    scope: "token.warn-token",
    settings: {
      foreground: "#CD9731",
    },
  },
  {
    scope: "token.error-token",
    settings: {
      foreground: "#F44747",
    },
  },
  {
    scope: "token.debug-token",
    settings: {
      foreground: "#B267E6",
    },
  },
] as const;

const _vesperThemeColors = {
  "activityBar.background": "#f5f5f5",
  "activityBar.foreground": "#505050",
  "activityBarBadge.background": "#ff8c00",
  "activityBarBadge.foreground": "#000000",
  "badge.background": "#ff8c00",
  "badge.foreground": "#000000",
  "button.background": "#ff8c00",
  "button.foreground": "#000000",
  "button.hoverBackground": "#ff9e40",
  "diffEditor.insertedLineBackground": "#99ffe415",
  "diffEditor.insertedTextBackground": "#99ffe415",
  "diffEditor.removedLineBackground": "#ff808015",
  "diffEditor.removedTextBackground": "#ff808015",
  "editor.background": "#ffffff",
  "editor.foreground": "#000000",
  "editor.selectionBackground": "#ff8c0020",
  "editor.selectionHighlightBackground": "#ff8c0020",
  "editorBracketHighlight.foreground1": "#707070",
  "editorBracketHighlight.foreground2": "#707070",
  "editorBracketHighlight.foreground3": "#707070",
  "editorBracketHighlight.foreground4": "#707070",
  "editorBracketHighlight.foreground5": "#707070",
  "editorBracketHighlight.foreground6": "#707070",
  "editorBracketHighlight.unexpectedBracket.foreground": "#ff8080",
  "editorError.foreground": "#ff8080",
  "editorGroupHeader.tabsBackground": "#f5f5f5",
  "editorGutter.addedBackground": "#99ffe4",
  "editorGutter.deletedBackground": "#ff8080",
  "editorGutter.modifiedBackground": "#ff8c00",
  "editorHoverWidget.background": "#ffffff",
  "editorHoverWidget.border": "#e0e0e0",
  "editorInlayHint.background": "#eaeaea",
  "editorInlayHint.foreground": "#707070",
  "editorLineNumber.foreground": "#707070",
  "editorOverviewRuler.border": "#e0e0e0",
  "editorWarning.foreground": "#ff8c00",
  "editorWidget.background": "#f5f5f5",
  focusBorder: "#ff8c00",
  "icon.foreground": "#505050",
  "input.background": "#ffffff",
  "list.activeSelectionBackground": "#ff8c0020",
  "list.activeSelectionForeground": "#ff8c00",
  "list.errorForeground": "#ff8080",
  "list.filterMatchBackground": "#ff8c0020",
  "list.highlightForeground": "#ff8c00",
  "list.hoverBackground": "#eaeaea",
  "list.inactiveSelectionBackground": "#e0e0e0",
  "quickInput.foreground": "#000000",
  "quickInputList.focusBackground": "#ff8c0020",
  "quickInputList.focusForeground": "#000000",
  "scrollbarSlider.background": "#c0c0c080",
  "scrollbarSlider.hoverBackground": "#c0c0c0",
  "selection.background": "#ff8c0020",
  "settings.modifiedItemIndicator": "#ff8c00",
  "sideBar.background": "#f5f5f5",
  "sideBarSectionHeader.background": "#f5f5f5",
  "sideBarSectionHeader.foreground": "#505050",
  "sideBarTitle.foreground": "#505050",
  "statusBar.background": "#f5f5f5",
  "statusBar.debuggingBackground": "#ff7300",
  "statusBar.debuggingForeground": "#000000",
  "statusBar.foreground": "#505050",
  "statusBarItem.remoteBackground": "#ff8c00",
  "statusBarItem.remoteForeground": "#000000",
  "tab.activeBackground": "#ffffff",
  "tab.border": "#f5f5f5",
  "tab.inactiveBackground": "#f5f5f5",
  "textLink.activeForeground": "#ff9e40",
  "textLink.foreground": "#ff8c00",
  "titleBar.activeBackground": "#f5f5f5",
  "titleBar.activeForeground": "#303030",
  "titleBar.inactiveBackground": "#f5f5f5",
  "titleBar.inactiveForeground": "#404040",
  //"actionBar.toggledBackground": "#ff8c0033",
  //"activityBar.activeBorder": "#505050",
  //"activityBar.dropBorder": "#505050",
  //"activityBar.inactiveForeground": "#50505066",
  //"activityBarTop.activeBorder": "#424242",
  //"activityBarTop.dropBorder": "#424242",
  //"activityBarTop.foreground": "#424242",
  //"activityBarTop.inactiveForeground": "#424242bf",
  //"activityErrorBadge.background": "#e51400",
  //"activityErrorBadge.foreground": "#ffffff",
  //"activityWarningBadge.background": "#b27c00",
  //"activityWarningBadge.foreground": "#ffffff",
  //"agentSessionReadIndicator.foreground": "#61616126",
  //"agentSessionSelectedBadge.border": "#ff8c004d",
  //"agentSessionSelectedUnfocusedBadge.border": "#6161614d",
  //"banner.background": "#b3620020",
  //"banner.foreground": "#ff8c00",
  //"banner.iconForeground": "#0063d3",
  //"breadcrumb.activeSelectionForeground": "#4e4e4e",
  //"breadcrumb.background": "#ffffff",
  //"breadcrumb.focusForeground": "#4e4e4e",
  //"breadcrumb.foreground": "#616161cc",
  //"breadcrumbPicker.background": "#f5f5f5",
  //"button.secondaryBackground": "#eaeaea",
  //"button.secondaryForeground": "#616161",
  //"button.secondaryHoverBackground": "#ffffff",
  //"button.separator": "#00000066",
  //"chart.axis": "#00000099",
  //"chart.guide": "#00000033",
  //"chart.line": "#236b8e",
  //"charts.blue": "#0063d3",
  //"charts.foreground": "#616161",
  //"charts.green": "#388a34",
  //"charts.lines": "#61616180",
  //"charts.orange": "#ea5c0055",
  //"charts.purple": "#652d90",
  //"charts.red": "#ff8080",
  //"charts.yellow": "#ff8c00",
  //"chat.avatarBackground": "#f2f2f2",
  //"chat.avatarForeground": "#616161",
  //"chat.checkpointSeparator": "#a9a9a9",
  //"chat.editedFileForeground": "#895503",
  //"chat.linesAddedForeground": "#107c10",
  //"chat.linesRemovedForeground": "#bc2f32",
  //"chat.requestBackground": "#ffffff9e",
  //"chat.requestBorder": "#0000001a",
  //"chat.requestBubbleBackground": "#ff8c000a",
  //"chat.requestBubbleHoverBackground": "#ff8c0013",
  //"chat.requestCodeBorder": "#0e639c40",
  //"chat.slashCommandBackground": "#adceff7a",
  //"chat.slashCommandForeground": "#26569e",
  //"chat.thinkingShimmer": "#000000",
  //"chatManagement.sashBorder": "#80808059",
  //"checkbox.background": "#ffffff",
  //"checkbox.border": "#cecece",
  //"checkbox.disabled.background": "#cacaca",
  //"checkbox.disabled.foreground": "#959595",
  //"checkbox.foreground": "#616161",
  //"checkbox.selectBackground": "#f5f5f5",
  //"checkbox.selectBorder": "#505050",
  //"commandCenter.activeBackground": "#00000014",
  //"commandCenter.activeBorder": "#3030304d",
  //"commandCenter.activeForeground": "#303030",
  //"commandCenter.background": "#0000000d",
  //"commandCenter.border": "#30303033",
  //"commandCenter.debuggingBackground": "#ff730042",
  //"commandCenter.foreground": "#303030",
  //"commandCenter.inactiveBorder": "#40404040",
  //"commandCenter.inactiveForeground": "#404040",
  //"commentsView.resolvedIcon": "#61616180",
  //"commentsView.unresolvedIcon": "#ff8c00",
  //"debugConsole.errorForeground": "#a1260d",
  //"debugConsole.infoForeground": "#0063d3",
  //"debugConsole.sourceForeground": "#616161",
  //"debugConsole.warningForeground": "#ff8c00",
  //"debugConsoleInputIcon.foreground": "#616161",
  //"debugExceptionWidget.background": "#f1dfde",
  //"debugExceptionWidget.border": "#a31515",
  //"debugIcon.breakpointCurrentStackframeForeground": "#be8700",
  //"debugIcon.breakpointDisabledForeground": "#848484",
  //"debugIcon.breakpointForeground": "#e51400",
  //"debugIcon.breakpointStackframeForeground": "#89d185",
  //"debugIcon.breakpointUnverifiedForeground": "#848484",
  //"debugIcon.continueForeground": "#007acc",
  //"debugIcon.disconnectForeground": "#a1260d",
  //"debugIcon.pauseForeground": "#007acc",
  //"debugIcon.restartForeground": "#388a34",
  //"debugIcon.startForeground": "#388a34",
  //"debugIcon.stepBackForeground": "#007acc",
  //"debugIcon.stepIntoForeground": "#007acc",
  //"debugIcon.stepOutForeground": "#007acc",
  //"debugIcon.stepOverForeground": "#007acc",
  //"debugIcon.stopForeground": "#a1260d",
  //"debugTokenExpression.boolean": "#0000ff",
  //"debugTokenExpression.error": "#e51400",
  //"debugTokenExpression.name": "#9b46b0",
  //"debugTokenExpression.number": "#098658",
  //"debugTokenExpression.string": "#a31515",
  //"debugTokenExpression.type": "#4a90e2",
  //"debugTokenExpression.value": "#6c6c6ccc",
  //"debugToolBar.background": "#f3f3f3",
  //"debugView.exceptionLabelBackground": "#a31515",
  //"debugView.exceptionLabelForeground": "#ffffff",
  //"debugView.stateLabelBackground": "#88888844",
  //"debugView.stateLabelForeground": "#616161",
  //"debugView.valueChangedHighlight": "#569cd6",
  //"descriptionForeground": "#717171",
  //"diffEditor.diagonalFill": "#22222233",
  //"diffEditor.move.border": "#8b8b8b9c",
  //"diffEditor.moveActive.border": "#ffa500",
  //"diffEditor.unchangedCodeBackground": "#b8b8b829",
  //"diffEditor.unchangedRegionBackground": "#f5f5f5",
  //"diffEditor.unchangedRegionForeground": "#616161",
  //"diffEditor.unchangedRegionShadow": "#737373bf",
  //"disabledForeground": "#61616180",
  //"dropdown.background": "#ffffff",
  //"dropdown.border": "#cecece",
  //"dropdown.foreground": "#616161",
  //"editor.compositionBorder": "#000000",
  //"editor.findMatchBackground": "#a8ac94",
  //"editor.findMatchHighlightBackground": "#ea5c0055",
  //"editor.findRangeHighlightBackground": "#b4b4b44d",
  //"editor.focusedStackFrameHighlightBackground": "#cee7ce73",
  //"editor.foldBackground": "#ff8c000a",
  //"editor.foldPlaceholderForeground": "#808080",
  //"editor.hoverHighlightBackground": "#add6ff26",
  //"editor.inactiveSelectionBackground": "#ff8c0010",
  //"editor.inlineValuesBackground": "#ffc80033",
  //"editor.inlineValuesForeground": "#00000080",
  //"editor.lineHighlightBorder": "#eeeeee",
  //"editor.linkedEditingBackground": "#ff00004d",
  //"editor.placeholder.foreground": "#00000077",
  //"editor.rangeHighlightBackground": "#fdff0033",
  //"editor.snippetFinalTabstopHighlightBorder": "#0a326480",
  //"editor.snippetTabstopHighlightBackground": "#0a326433",
  //"editor.stackFrameHighlightBackground": "#ffff6673",
  //"editor.symbolHighlightBackground": "#ea5c0055",
  //"editor.wordHighlightBackground": "#57575740",
  //"editor.wordHighlightStrongBackground": "#0e639c40",
  //"editor.wordHighlightTextBackground": "#57575740",
  //"editorActionList.background": "#f5f5f5",
  //"editorActionList.focusBackground": "#ff8c0020",
  //"editorActionList.focusForeground": "#ff8c00",
  //"editorActionList.foreground": "#616161",
  //"editorBracketMatch.background": "#0064001a",
  //"editorBracketMatch.border": "#b9b9b9",
  //"editorBracketPairGuide.activeBackground1": "#00000000",
  //"editorBracketPairGuide.activeBackground2": "#00000000",
  //"editorBracketPairGuide.activeBackground3": "#00000000",
  //"editorBracketPairGuide.activeBackground4": "#00000000",
  //"editorBracketPairGuide.activeBackground5": "#00000000",
  //"editorBracketPairGuide.activeBackground6": "#00000000",
  //"editorBracketPairGuide.background1": "#00000000",
  //"editorBracketPairGuide.background2": "#00000000",
  //"editorBracketPairGuide.background3": "#00000000",
  //"editorBracketPairGuide.background4": "#00000000",
  //"editorBracketPairGuide.background5": "#00000000",
  //"editorBracketPairGuide.background6": "#00000000",
  //"editorCodeLens.foreground": "#919191",
  //"editorCommentsWidget.rangeActiveBackground": "#ff8c001a",
  //"editorCommentsWidget.rangeBackground": "#ff8c001a",
  //"editorCommentsWidget.replyInputBackground": "#f3f3f3",
  //"editorCommentsWidget.resolvedBorder": "#61616180",
  //"editorCommentsWidget.unresolvedBorder": "#ff8c00",
  //"editorCursor.foreground": "#000000",
  //"editorGhostText.foreground": "#00000077",
  //"editorGroup.border": "#e7e7e7",
  //"editorGroup.dropBackground": "#2677cb2e",
  //"editorGroup.dropIntoPromptBackground": "#f5f5f5",
  //"editorGroup.dropIntoPromptForeground": "#616161",
  //"editorGroupHeader.noTabsBackground": "#ffffff",
  //"editorGutter.addedSecondaryBackground": "#ffffff",
  //"editorGutter.background": "#ffffff",
  //"editorGutter.commentDraftGlyphForeground": "#000000",
  //"editorGutter.commentGlyphForeground": "#000000",
  //"editorGutter.commentRangeForeground": "#d5d5d5",
  //"editorGutter.commentUnresolvedGlyphForeground": "#000000",
  //"editorGutter.deletedSecondaryBackground": "#fff3f3",
  //"editorGutter.foldingControlForeground": "#505050",
  //"editorGutter.itemBackground": "#d5d5d5",
  //"editorGutter.itemGlyphForeground": "#000000",
  //"editorGutter.modifiedSecondaryBackground": "#ffddb3",
  //"editorHint.foreground": "#6c6c6c",
  //"editorHoverWidget.foreground": "#616161",
  //"editorHoverWidget.highlightForeground": "#ff8c00",
  //"editorHoverWidget.statusBarBackground": "#f2f2f2",
  //"editorIndentGuide.activeBackground1": "#33333333",
  //"editorIndentGuide.activeBackground2": "#00000000",
  //"editorIndentGuide.activeBackground3": "#00000000",
  //"editorIndentGuide.activeBackground4": "#00000000",
  //"editorIndentGuide.activeBackground5": "#00000000",
  //"editorIndentGuide.activeBackground6": "#00000000",
  //"editorIndentGuide.background1": "#33333333",
  //"editorIndentGuide.background2": "#00000000",
  //"editorIndentGuide.background3": "#00000000",
  //"editorIndentGuide.background4": "#00000000",
  //"editorIndentGuide.background5": "#00000000",
  //"editorIndentGuide.background6": "#00000000",
  //"editorInfo.foreground": "#0063d3",
  //"editorInlayHint.parameterBackground": "#eaeaea",
  //"editorInlayHint.parameterForeground": "#707070",
  //"editorInlayHint.typeBackground": "#eaeaea",
  //"editorInlayHint.typeForeground": "#707070",
  //"editorLightBulb.foreground": "#ddb100",
  //"editorLightBulbAi.foreground": "#ddb100",
  //"editorLightBulbAutoFix.foreground": "#007acc",
  //"editorLineNumber.activeForeground": "#0b216f",
  //"editorLink.activeForeground": "#0000ff",
  //"editorMarkerNavigation.background": "#ffffff",
  //"editorMarkerNavigationError.background": "#ff8080",
  //"editorMarkerNavigationError.headerBackground": "#ff80801a",
  //"editorMarkerNavigationInfo.background": "#0063d3",
  //"editorMarkerNavigationInfo.headerBackground": "#0063d31a",
  //"editorMarkerNavigationWarning.background": "#ff8c00",
  //"editorMarkerNavigationWarning.headerBackground": "#ff8c001a",
  //"editorMinimap.inlineChatInserted": "#99ffe411",
  //"editorMultiCursor.primary.foreground": "#000000",
  //"editorMultiCursor.secondary.foreground": "#000000",
  //"editorOverviewRuler.addedForeground": "#99ffe499",
  //"editorOverviewRuler.bracketMatchForeground": "#a0a0a0",
  //"editorOverviewRuler.commentDraftForeground": "#d5d5d5",
  //"editorOverviewRuler.commentForeground": "#d5d5d5",
  //"editorOverviewRuler.commentUnresolvedForeground": "#d5d5d5",
  //"editorOverviewRuler.commonContentForeground": "#60606066",
  //"editorOverviewRuler.currentContentForeground": "#40c8ae80",
  //"editorOverviewRuler.deletedForeground": "#ff808099",
  //"editorOverviewRuler.errorForeground": "#ff1212b3",
  //"editorOverviewRuler.findMatchForeground": "#d186167e",
  //"editorOverviewRuler.incomingContentForeground": "#40a6ff80",
  //"editorOverviewRuler.infoForeground": "#0063d3",
  //"editorOverviewRuler.inlineChatInserted": "#99ffe411",
  //"editorOverviewRuler.inlineChatRemoved": "#ff808011",
  //"editorOverviewRuler.modifiedForeground": "#ff8c0099",
  //"editorOverviewRuler.rangeHighlightForeground": "#007acc99",
  //"editorOverviewRuler.selectionHighlightForeground": "#a0a0a0cc",
  //"editorOverviewRuler.warningForeground": "#ff8c00",
  //"editorOverviewRuler.wordHighlightForeground": "#a0a0a0cc",
  //"editorOverviewRuler.wordHighlightStrongForeground": "#c0a0c0cc",
  //"editorOverviewRuler.wordHighlightTextForeground": "#a0a0a0cc",
  //"editorPane.background": "#ffffff",
  //"editorRuler.foreground": "#d3d3d3",
  //"editorStickyScroll.background": "#ffffff",
  //"editorStickyScroll.shadow": "#dddddd",
  //"editorStickyScrollGutter.background": "#ffffff",
  //"editorStickyScrollHover.background": "#f0f0f0",
  //"editorSuggestWidget.background": "#f5f5f5",
  //"editorSuggestWidget.border": "#c8c8c8",
  //"editorSuggestWidget.focusHighlightForeground": "#ff8c00",
  //"editorSuggestWidget.foreground": "#000000",
  //"editorSuggestWidget.highlightForeground": "#ff8c00",
  //"editorSuggestWidget.selectedBackground": "#ff8c0020",
  //"editorSuggestWidget.selectedForeground": "#000000",
  //"editorSuggestWidgetStatus.foreground": "#00000080",
  //"editorUnicodeHighlight.border": "#ff8c00",
  //"editorUnnecessaryCode.opacity": "#00000077",
  //"editorWhitespace.foreground": "#33333333",
  //"editorWidget.border": "#c8c8c8",
  //"editorWidget.foreground": "#616161",
  //"errorForeground": "#a1260d",
  //"errorLens.errorBackground": "#e4545420",
  //"errorLens.errorBackgroundLight": "#e4545420",
  //"errorLens.errorForeground": "#e45454",
  //"errorLens.errorForegroundLight": "#e45454",
  //"errorLens.errorMessageBackground": "#e4545419",
  //"errorLens.errorRangeBackground": "#e4545419",
  //"errorLens.hintBackground": "#17a2a220",
  //"errorLens.hintBackgroundLight": "#17a2a220",
  //"errorLens.hintForeground": "#2faf64",
  //"errorLens.hintForegroundLight": "#2faf64",
  //"errorLens.hintMessageBackground": "#17a2a219",
  //"errorLens.hintRangeBackground": "#17a2a219",
  //"errorLens.infoBackground": "#00b7e420",
  //"errorLens.infoBackgroundLight": "#00b7e420",
  //"errorLens.infoForeground": "#00b7e4",
  //"errorLens.infoForegroundLight": "#00b7e4",
  //"errorLens.infoMessageBackground": "#00b7e419",
  //"errorLens.infoRangeBackground": "#00b7e419",
  //"errorLens.statusBarErrorForeground": "#e45454",
  //"errorLens.statusBarHintForeground": "#2faf64",
  //"errorLens.statusBarIconErrorForeground": "#e45454",
  //"errorLens.statusBarIconWarningForeground": "#ff942f",
  //"errorLens.statusBarInfoForeground": "#00b7e4",
  //"errorLens.statusBarWarningForeground": "#ff942f",
  //"errorLens.warningBackground": "#ff942f20",
  //"errorLens.warningBackgroundLight": "#ff942f20",
  //"errorLens.warningForeground": "#ff942f",
  //"errorLens.warningForegroundLight": "#ff942f",
  //"errorLens.warningMessageBackground": "#ff942f19",
  //"errorLens.warningRangeBackground": "#ff942f19",
  //"extensionBadge.remoteBackground": "#ff8c00",
  //"extensionBadge.remoteForeground": "#000000",
  //"extensionButton.background": "#eaeaea",
  //"extensionButton.foreground": "#616161",
  //"extensionButton.hoverBackground": "#ffffff",
  //"extensionButton.prominentBackground": "#ff8c00",
  //"extensionButton.prominentForeground": "#000000",
  //"extensionButton.prominentHoverBackground": "#ff9e40",
  //"extensionButton.separator": "#00000066",
  //"extensionIcon.preReleaseForeground": "#1d9271",
  //"extensionIcon.privateForeground": "#00000060",
  //"extensionIcon.sponsorForeground": "#b51e78",
  //"extensionIcon.starForeground": "#df6100",
  //"extensionIcon.verifiedForeground": "#ff8c00",
  //"foreground": "#616161",
  //"gauge.background": "#007acc4d",
  //"gauge.errorBackground": "#be11004d",
  //"gauge.errorForeground": "#be1100",
  //"gauge.foreground": "#007acc",
  //"gauge.warningBackground": "#b895004d",
  //"gauge.warningForeground": "#b89500",
  //"git.blame.editorDecorationForeground": "#707070",
  //"gitDecoration.addedResourceForeground": "#587c0c",
  //"gitDecoration.conflictingResourceForeground": "#ad0707",
  //"gitDecoration.deletedResourceForeground": "#ad0707",
  //"gitDecoration.ignoredResourceForeground": "#8e8e90",
  //"gitDecoration.modifiedResourceForeground": "#895503",
  //"gitDecoration.renamedResourceForeground": "#007100",
  //"gitDecoration.stageDeletedResourceForeground": "#ad0707",
  //"gitDecoration.stageModifiedResourceForeground": "#895503",
  //"gitDecoration.submoduleResourceForeground": "#1258a7",
  //"gitDecoration.untrackedResourceForeground": "#007100",
  //"github.issues.closed": "#8957e5",
  //"gitlens.closedAutolinkedIssueIconColor": "#8250df",
  //"gitlens.closedPullRequestIconColor": "#cf222e",
  //"gitlens.decorations.addedForegroundColor": "#587c0c",
  //"gitlens.decorations.branchAheadForegroundColor": "#35b15e",
  //"gitlens.decorations.branchBehindForegroundColor": "#b15e35",
  //"gitlens.decorations.branchDivergedForegroundColor": "#d8af1b",
  //"gitlens.decorations.branchMissingUpstreamForegroundColor": "#ad0707",
  //"gitlens.decorations.copiedForegroundColor": "#007100",
  //"gitlens.decorations.deletedForegroundColor": "#ad0707",
  //"gitlens.decorations.ignoredForegroundColor": "#8e8e90",
  //"gitlens.decorations.modifiedForegroundColor": "#895503",
  //"gitlens.decorations.renamedForegroundColor": "#007100",
  //"gitlens.decorations.statusMergingOrRebasingConflictForegroundColor": "#ad0707",
  //"gitlens.decorations.statusMergingOrRebasingForegroundColor": "#d8af1b",
  //"gitlens.decorations.untrackedForegroundColor": "#007100",
  //"gitlens.decorations.workspaceCurrentForegroundColor": "#35b15e",
  //"gitlens.decorations.workspaceRepoMissingForegroundColor": "#949494",
  //"gitlens.decorations.workspaceRepoOpenForegroundColor": "#35b15e",
  //"gitlens.decorations.worktreeHasUncommittedChangesForegroundColor": "#895503",
  //"gitlens.decorations.worktreeMissingForegroundColor": "#ad0707",
  //"gitlens.graphChangesColumnAddedColor": "#2da44e",
  //"gitlens.graphChangesColumnDeletedColor": "#cf222e",
  //"gitlens.graphLane10Color": "#2ece9d",
  //"gitlens.graphLane1Color": "#15a0bf",
  //"gitlens.graphLane2Color": "#0669f7",
  //"gitlens.graphLane3Color": "#8e00c2",
  //"gitlens.graphLane4Color": "#c517b6",
  //"gitlens.graphLane5Color": "#d90171",
  //"gitlens.graphLane6Color": "#cd0101",
  //"gitlens.graphLane7Color": "#f25d2e",
  //"gitlens.graphLane8Color": "#f2ca33",
  //"gitlens.graphLane9Color": "#7bd938",
  //"gitlens.graphMinimapMarkerHeadColor": "#04c814",
  //"gitlens.graphMinimapMarkerHighlightsColor": "#f5cc00",
  //"gitlens.graphMinimapMarkerLocalBranchesColor": "#3095e8",
  //"gitlens.graphMinimapMarkerPullRequestsColor": "#ff8f18",
  //"gitlens.graphMinimapMarkerRemoteBranchesColor": "#67ace4",
  //"gitlens.graphMinimapMarkerStashesColor": "#e467e4",
  //"gitlens.graphMinimapMarkerTagsColor": "#d2a379",
  //"gitlens.graphMinimapMarkerUpstreamColor": "#8cd993",
  //"gitlens.graphScrollMarkerHeadColor": "#04c814",
  //"gitlens.graphScrollMarkerHighlightsColor": "#f5cc00",
  //"gitlens.graphScrollMarkerLocalBranchesColor": "#3095e8",
  //"gitlens.graphScrollMarkerPullRequestsColor": "#ff8f18",
  //"gitlens.graphScrollMarkerRemoteBranchesColor": "#67ace4",
  //"gitlens.graphScrollMarkerStashesColor": "#e467e4",
  //"gitlens.graphScrollMarkerTagsColor": "#d2a379",
  //"gitlens.graphScrollMarkerUpstreamColor": "#8cd993",
  //"gitlens.gutterBackgroundColor": "#0000000c",
  //"gitlens.gutterForegroundColor": "#747474",
  //"gitlens.gutterUncommittedForegroundColor": "#00bcf299",
  //"gitlens.launchpadIndicatorAttentionColor": "#cc9b15",
  //"gitlens.launchpadIndicatorAttentionHoverColor": "#cc9b15",
  //"gitlens.launchpadIndicatorBlockedColor": "#ad0707",
  //"gitlens.launchpadIndicatorBlockedHoverColor": "#ad0707",
  //"gitlens.launchpadIndicatorMergeableColor": "#42c954",
  //"gitlens.launchpadIndicatorMergeableHoverColor": "#42c954",
  //"gitlens.lineHighlightBackgroundColor": "#00bcf233",
  //"gitlens.lineHighlightOverviewRulerColor": "#00bcf299",
  //"gitlens.mergedPullRequestIconColor": "#8250df",
  //"gitlens.openAutolinkedIssueIconColor": "#1a7f37",
  //"gitlens.openPullRequestIconColor": "#1a7f37",
  //"gitlens.trailingLineBackgroundColor": "#00000000",
  //"gitlens.trailingLineForegroundColor": "#99999959",
  //"gitlens.unpublishedChangesIconColor": "#35b15e",
  //"gitlens.unpublishedCommitIconColor": "#35b15e",
  //"gitlens.unpulledChangesIconColor": "#b15e35",
  //"inlineChat.background": "#f5f5f5",
  //"inlineChat.border": "#c8c8c8",
  //"inlineChat.foreground": "#616161",
  //"inlineChat.shadow": "#00000029",
  //"inlineChatDiff.inserted": "#99ffe40a",
  //"inlineChatDiff.removed": "#ff80800a",
  //"inlineChatInput.background": "#ffffff",
  //"inlineChatInput.border": "#c8c8c8",
  //"inlineChatInput.focusBorder": "#ff8c00",
  //"inlineChatInput.placeholderForeground": "#61616180",
  //"inlineEdit.gutterIndicator.background": "#5f5f5f18",
  //"inlineEdit.gutterIndicator.primaryBackground": "#ff8c0080",
  //"inlineEdit.gutterIndicator.primaryBorder": "#ff8c00",
  //"inlineEdit.gutterIndicator.primaryForeground": "#000000",
  //"inlineEdit.gutterIndicator.secondaryBackground": "#ffffff",
  //"inlineEdit.gutterIndicator.secondaryBorder": "#e0e0e0",
  //"inlineEdit.gutterIndicator.secondaryForeground": "#616161",
  //"inlineEdit.gutterIndicator.successfulBackground": "#ff8c00",
  //"inlineEdit.gutterIndicator.successfulBorder": "#ff8c00",
  //"inlineEdit.gutterIndicator.successfulForeground": "#000000",
  //"inlineEdit.modifiedBackground": "#99ffe406",
  //"inlineEdit.modifiedBorder": "#00a37815",
  //"inlineEdit.modifiedChangedLineBackground": "#99ffe40f",
  //"inlineEdit.modifiedChangedTextBackground": "#99ffe40f",
  //"inlineEdit.originalBackground": "#ff808004",
  //"inlineEdit.originalBorder": "#ff808015",
  //"inlineEdit.originalChangedLineBackground": "#ff808011",
  //"inlineEdit.originalChangedTextBackground": "#ff808011",
  //"inlineEdit.tabWillAcceptModifiedBorder": "#00a37815",
  //"inlineEdit.tabWillAcceptOriginalBorder": "#ff808015",
  //"input.foreground": "#616161",
  //"input.placeholderForeground": "#61616180",
  //"inputOption.activeBackground": "#ff8c0033",
  //"inputOption.activeBorder": "#007acc",
  //"inputOption.activeForeground": "#000000",
  //"inputOption.hoverBackground": "#b8b8b850",
  //"inputValidation.errorBackground": "#f2dede",
  //"inputValidation.errorBorder": "#be1100",
  //"inputValidation.infoBackground": "#d6ecf2",
  //"inputValidation.infoBorder": "#007acc",
  //"inputValidation.warningBackground": "#f6f5d2",
  //"inputValidation.warningBorder": "#b89500",
  //"interactive.activeCodeBorder": "#007acc",
  //"interactive.inactiveCodeBorder": "#e0e0e0",
  //"issues.closed": "#8957e5",
  //"issues.newIssueDecoration": "#00000048",
  //"issues.open": "#3fb950",
  //"keybindingLabel.background": "#dddddd66",
  //"keybindingLabel.border": "#cccccc66",
  //"keybindingLabel.bottomBorder": "#bbbbbb66",
  //"keybindingLabel.foreground": "#555555",
  //"keybindingTable.headerBackground": "#6161610a",
  //"keybindingTable.rowsBackground": "#6161610a",
  //"list.deemphasizedForeground": "#8e8e90",
  //"list.dropBackground": "#d6ebff",
  //"list.dropBetweenBackground": "#505050",
  //"list.focusHighlightForeground": "#ff8c00",
  //"list.focusOutline": "#ff8c00",
  //"list.invalidItemForeground": "#b89500",
  //"list.warningForeground": "#855f00",
  //"listFilterWidget.background": "#f5f5f5",
  //"listFilterWidget.noMatchesOutline": "#be1100",
  //"listFilterWidget.outline": "#00000000",
  //"listFilterWidget.shadow": "#00000029",
  //"markdownAlert.caution.foreground": "#ff8080",
  //"markdownAlert.important.foreground": "#652d90",
  //"markdownAlert.note.foreground": "#0063d3",
  //"markdownAlert.tip.foreground": "#388a34",
  //"markdownAlert.warning.foreground": "#ff8c00",
  //"mcpIcon.starForeground": "#df6100",
  //"menu.background": "#ffffff",
  //"menu.foreground": "#616161",
  //"menu.selectionBackground": "#ff8c0020",
  //"menu.selectionForeground": "#ff8c00",
  //"menu.separatorBackground": "#d4d4d4",
  //"menubar.selectionBackground": "#b8b8b850",
  //"menubar.selectionForeground": "#303030",
  //"merge.commonContentBackground": "#60606029",
  //"merge.commonHeaderBackground": "#60606066",
  //"merge.currentContentBackground": "#40c8ae33",
  //"merge.currentHeaderBackground": "#40c8ae80",
  //"merge.incomingContentBackground": "#40a6ff33",
  //"merge.incomingHeaderBackground": "#40a6ff80",
  //"mergeEditor.change.background": "#9bb95533",
  //"mergeEditor.change.word.background": "#9ccc2c66",
  //"mergeEditor.changeBase.background": "#ffcccc",
  //"mergeEditor.changeBase.word.background": "#ffa3a3",
  //"mergeEditor.conflict.handled.minimapOverViewRuler": "#adaca8ee",
  //"mergeEditor.conflict.handledFocused.border": "#c1c1c1cc",
  //"mergeEditor.conflict.handledUnfocused.border": "#86868649",
  //"mergeEditor.conflict.input1.background": "#40c8ae33",
  //"mergeEditor.conflict.input2.background": "#40a6ff33",
  //"mergeEditor.conflict.unhandled.minimapOverViewRuler": "#fcba03",
  //"mergeEditor.conflict.unhandledFocused.border": "#ffa600",
  //"mergeEditor.conflict.unhandledUnfocused.border": "#ffa600",
  //"mergeEditor.conflictingLines.background": "#ffea0047",
  //"minimap.chatEditHighlight": "#ffffff99",
  //"minimap.errorHighlight": "#ff1212b3",
  //"minimap.findMatchHighlight": "#ea5c0055",
  //"minimap.foregroundOpacity": "#000000",
  //"minimap.infoHighlight": "#0063d3",
  //"minimap.selectionHighlight": "#ff8c0020",
  //"minimap.selectionOccurrenceHighlight": "#ff8c0020",
  //"minimap.warningHighlight": "#ff8c00",
  //"minimapGutter.addedBackground": "#99ffe4",
  //"minimapGutter.deletedBackground": "#ff8080",
  //"minimapGutter.modifiedBackground": "#ff8c00",
  //"minimapSlider.activeBackground": "#0000004d",
  //"minimapSlider.background": "#c0c0c040",
  //"minimapSlider.hoverBackground": "#c0c0c080",
  //"multiDiffEditor.background": "#ffffff",
  //"multiDiffEditor.border": "#cccccc",
  //"multiDiffEditor.headerBackground": "#f5f5f5",
  //"notebook.cellBorderColor": "#e0e0e0",
  //"notebook.cellEditorBackground": "#f5f5f5",
  //"notebook.cellInsertionIndicator": "#ff8c00",
  //"notebook.cellStatusBarItemHoverBackground": "#00000014",
  //"notebook.cellToolbarSeparator": "#80808059",
  //"notebook.editorBackground": "#ffffff",
  //"notebook.focusedCellBorder": "#ff8c00",
  //"notebook.focusedEditorBorder": "#ff8c00",
  //"notebook.inactiveFocusedCellBorder": "#e0e0e0",
  //"notebook.selectedCellBackground": "#e0e0e0",
  //"notebook.selectedCellBorder": "#e0e0e0",
  //"notebook.symbolHighlightBackground": "#fdff0033",
  //"notebookEditorOverviewRuler.runningCellForeground": "#388a34",
  //"notebookScrollbarSlider.activeBackground": "#00000099",
  //"notebookScrollbarSlider.background": "#c0c0c080",
  //"notebookScrollbarSlider.hoverBackground": "#c0c0c0",
  //"notebookStatusErrorIcon.foreground": "#a1260d",
  //"notebookStatusRunningIcon.foreground": "#616161",
  //"notebookStatusSuccessIcon.foreground": "#388a34",
  //"notificationCenterHeader.background": "#e9e9e9",
  //"notificationLink.foreground": "#ff8c00",
  //"notifications.background": "#f5f5f5",
  //"notifications.border": "#e9e9e9",
  //"notifications.foreground": "#616161",
  //"notificationsErrorIcon.foreground": "#ff8080",
  //"notificationsInfoIcon.foreground": "#0063d3",
  //"notificationsWarningIcon.foreground": "#ff8c00",
  //"panel.background": "#ffffff",
  //"panel.border": "#80808059",
  //"panel.dropBorder": "#424242",
  //"panelInput.border": "#dddddd",
  //"panelSection.border": "#80808059",
  //"panelSection.dropBackground": "#2677cb2e",
  //"panelSectionHeader.background": "#80808033",
  //"panelStickyScroll.background": "#ffffff",
  //"panelStickyScroll.shadow": "#dddddd",
  //"panelTitle.activeBorder": "#424242",
  //"panelTitle.activeForeground": "#424242",
  //"panelTitle.inactiveForeground": "#424242bf",
  //"panelTitleBadge.background": "#ff8c00",
  //"panelTitleBadge.foreground": "#000000",
  //"peekView.border": "#0063d3",
  //"peekViewEditor.background": "#f2f8fc",
  //"peekViewEditor.matchHighlightBackground": "#f5d802de",
  //"peekViewEditorGutter.background": "#f2f8fc",
  //"peekViewEditorStickyScroll.background": "#f2f8fc",
  //"peekViewEditorStickyScrollGutter.background": "#f2f8fc",
  //"peekViewResult.background": "#f3f3f3",
  //"peekViewResult.fileForeground": "#1e1e1e",
  //"peekViewResult.lineForeground": "#646465",
  //"peekViewResult.matchHighlightBackground": "#ea5c004d",
  //"peekViewResult.selectionBackground": "#3399ff33",
  //"peekViewResult.selectionForeground": "#6c6c6c",
  //"peekViewTitle.background": "#f3f3f3",
  //"peekViewTitleDescription.foreground": "#616161",
  //"peekViewTitleLabel.foreground": "#000000",
  //"pickerGroup.border": "#cccedb",
  //"pickerGroup.foreground": "#0066bf",
  //"ports.iconRunningProcessForeground": "#ff8c00",
  //"problemsErrorIcon.foreground": "#ff8080",
  //"problemsInfoIcon.foreground": "#0063d3",
  //"problemsWarningIcon.foreground": "#ff8c00",
  //"profileBadge.background": "#c4c4c4",
  //"profileBadge.foreground": "#333333",
  //"profiles.sashBorder": "#80808059",
  //"progressBar.background": "#0e70c0",
  //"pullRequests.closed": "#cb2431",
  //"pullRequests.draft": "#6e7681",
  //"pullRequests.merged": "#8957e5",
  //"pullRequests.notification": "#0063d3",
  //"pullRequests.open": "#3fb950",
  //"quickInput.background": "#f5f5f5",
  //"quickInputTitle.background": "#0000000f",
  //"radio.activeBackground": "#ff8c0033",
  //"radio.activeBorder": "#007acc",
  //"radio.activeForeground": "#000000",
  //"radio.inactiveBorder": "#00000033",
  //"radio.inactiveHoverBackground": "#b8b8b850",
  //"rainbowtrack1": "#ff0000",
  //"rainbowtrack2": "#00ff00",
  //"rainbowtrack3": "#0000ff",
  //"sash.hoverBorder": "#ff8c00",
  //"scmGraph.foreground1": "#ffb000",
  //"scmGraph.foreground2": "#dc267f",
  //"scmGraph.foreground3": "#994f00",
  //"scmGraph.foreground4": "#40b0a6",
  //"scmGraph.foreground5": "#b66dff",
  //"scmGraph.historyItemBaseRefColor": "#ea5c00",
  //"scmGraph.historyItemHoverAdditionsForeground": "#587c0c",
  //"scmGraph.historyItemHoverDefaultLabelBackground": "#ff8c00",
  //"scmGraph.historyItemHoverDefaultLabelForeground": "#616161",
  //"scmGraph.historyItemHoverDeletionsForeground": "#ad0707",
  //"scmGraph.historyItemHoverLabelForeground": "#ffffff",
  //"scmGraph.historyItemRefColor": "#0063d3",
  //"scmGraph.historyItemRemoteRefColor": "#652d90",
  //"scrollbar.shadow": "#dddddd",
  //"scrollbarSlider.activeBackground": "#00000099",
  //"search.resultsInfoForeground": "#616161",
  //"searchEditor.findMatchBackground": "#ea5c0038",
  //"settings.checkboxBackground": "#ffffff",
  //"settings.checkboxBorder": "#cecece",
  //"settings.checkboxForeground": "#616161",
  //"settings.dropdownBackground": "#ffffff",
  //"settings.dropdownBorder": "#cecece",
  //"settings.dropdownForeground": "#616161",
  //"settings.dropdownListBorder": "#c8c8c8",
  //"settings.focusedRowBackground": "#eaeaea99",
  //"settings.focusedRowBorder": "#ff8c00",
  //"settings.headerBorder": "#80808059",
  //"settings.headerForeground": "#444444",
  //"settings.numberInputBackground": "#ffffff",
  //"settings.numberInputForeground": "#616161",
  //"settings.rowHoverBackground": "#eaeaea4d",
  //"settings.sashBorder": "#80808059",
  //"settings.settingsHeaderHoverForeground": "#444444b3",
  //"settings.textInputBackground": "#ffffff",
  //"settings.textInputForeground": "#616161",
  //"sideBar.dropBackground": "#2677cb2e",
  //"sideBarStickyScroll.background": "#f5f5f5",
  //"sideBarStickyScroll.shadow": "#dddddd",
  //"sideBarTitle.background": "#f5f5f5",
  //"sideBySideEditor.horizontalBorder": "#e7e7e7",
  //"sideBySideEditor.verticalBorder": "#e7e7e7",
  //"simpleFindWidget.sashBorder": "#c8c8c8",
  //"statusBar.focusBorder": "#505050",
  //"statusBar.noFolderBackground": "#68217a",
  //"statusBar.noFolderForeground": "#505050",
  //"statusBarItem.activeBackground": "#ffffff2e",
  //"statusBarItem.compactHoverBackground": "#0000001f",
  //"statusBarItem.errorBackground": "#611708",
  //"statusBarItem.errorForeground": "#ffffff",
  //"statusBarItem.errorHoverBackground": "#0000001f",
  //"statusBarItem.errorHoverForeground": "#505050",
  //"statusBarItem.focusBorder": "#505050",
  //"statusBarItem.hoverBackground": "#0000001f",
  //"statusBarItem.hoverForeground": "#505050",
  //"statusBarItem.offlineBackground": "#6c1717",
  //"statusBarItem.offlineForeground": "#000000",
  //"statusBarItem.offlineHoverBackground": "#0000001f",
  //"statusBarItem.offlineHoverForeground": "#505050",
  //"statusBarItem.prominentBackground": "#00000080",
  //"statusBarItem.prominentForeground": "#505050",
  //"statusBarItem.prominentHoverBackground": "#0000001f",
  //"statusBarItem.prominentHoverForeground": "#505050",
  //"statusBarItem.remoteHoverBackground": "#0000001f",
  //"statusBarItem.remoteHoverForeground": "#505050",
  //"statusBarItem.warningBackground": "#995400",
  //"statusBarItem.warningForeground": "#ffffff",
  //"statusBarItem.warningHoverBackground": "#0000001f",
  //"statusBarItem.warningHoverForeground": "#505050",
  //"symbolIcon.arrayForeground": "#616161",
  //"symbolIcon.booleanForeground": "#616161",
  //"symbolIcon.classForeground": "#d67e00",
  //"symbolIcon.colorForeground": "#616161",
  //"symbolIcon.constantForeground": "#616161",
  //"symbolIcon.constructorForeground": "#652d90",
  //"symbolIcon.enumeratorForeground": "#d67e00",
  //"symbolIcon.enumeratorMemberForeground": "#007acc",
  //"symbolIcon.eventForeground": "#d67e00",
  //"symbolIcon.fieldForeground": "#007acc",
  //"symbolIcon.fileForeground": "#616161",
  //"symbolIcon.folderForeground": "#616161",
  //"symbolIcon.functionForeground": "#652d90",
  //"symbolIcon.interfaceForeground": "#007acc",
  //"symbolIcon.keyForeground": "#616161",
  //"symbolIcon.keywordForeground": "#616161",
  //"symbolIcon.methodForeground": "#652d90",
  //"symbolIcon.moduleForeground": "#616161",
  //"symbolIcon.namespaceForeground": "#616161",
  //"symbolIcon.nullForeground": "#616161",
  //"symbolIcon.numberForeground": "#616161",
  //"symbolIcon.objectForeground": "#616161",
  //"symbolIcon.operatorForeground": "#616161",
  //"symbolIcon.packageForeground": "#616161",
  //"symbolIcon.propertyForeground": "#616161",
  //"symbolIcon.referenceForeground": "#616161",
  //"symbolIcon.snippetForeground": "#616161",
  //"symbolIcon.stringForeground": "#616161",
  //"symbolIcon.structForeground": "#616161",
  //"symbolIcon.textForeground": "#616161",
  //"symbolIcon.typeParameterForeground": "#616161",
  //"symbolIcon.unitForeground": "#616161",
  //"symbolIcon.variableForeground": "#007acc",
  //"tab.activeForeground": "#333333",
  //"tab.activeModifiedBorder": "#33aaee",
  //"tab.dragAndDropBorder": "#333333",
  //"tab.inactiveForeground": "#333333b3",
  //"tab.inactiveModifiedBorder": "#33aaee80",
  //"tab.lastPinnedBorder": "#a9a9a9",
  //"tab.selectedBackground": "#ffffff",
  //"tab.selectedForeground": "#333333",
  //"tab.unfocusedActiveBackground": "#ffffff",
  //"tab.unfocusedActiveForeground": "#333333b3",
  //"tab.unfocusedActiveModifiedBorder": "#33aaeeb3",
  //"tab.unfocusedInactiveBackground": "#f5f5f5",
  //"tab.unfocusedInactiveForeground": "#33333359",
  //"tab.unfocusedInactiveModifiedBorder": "#33aaee40",
  //"terminal.ansiBlack": "#000000",
  //"terminal.ansiBlue": "#0451a5",
  //"terminal.ansiBrightBlack": "#666666",
  //"terminal.ansiBrightBlue": "#0451a5",
  //"terminal.ansiBrightCyan": "#0598bc",
  //"terminal.ansiBrightGreen": "#14ce14",
  //"terminal.ansiBrightMagenta": "#bc05bc",
  //"terminal.ansiBrightRed": "#cd3131",
  //"terminal.ansiBrightWhite": "#a5a5a5",
  //"terminal.ansiBrightYellow": "#b5ba00",
  //"terminal.ansiCyan": "#0598bc",
  //"terminal.ansiGreen": "#107c10",
  //"terminal.ansiMagenta": "#bc05bc",
  //"terminal.ansiRed": "#cd3131",
  //"terminal.ansiWhite": "#555555",
  //"terminal.ansiYellow": "#949800",
  //"terminal.border": "#80808059",
  //"terminal.dropBackground": "#2677cb2e",
  //"terminal.findMatchBackground": "#a8ac94",
  //"terminal.findMatchHighlightBackground": "#ea5c0055",
  //"terminal.foreground": "#333333",
  //"terminal.hoverHighlightBackground": "#add6ff13",
  //"terminal.inactiveSelectionBackground": "#ff8c0010",
  //"terminal.initialHintForeground": "#00000077",
  //"terminal.selectionBackground": "#ff8c0020",
  //"terminalCommandDecoration.defaultBackground": "#00000040",
  //"terminalCommandDecoration.errorBackground": "#e51400",
  //"terminalCommandDecoration.successBackground": "#2090d3",
  //"terminalCommandGuide.foreground": "#e0e0e0",
  //"terminalOverviewRuler.border": "#e0e0e0",
  //"terminalOverviewRuler.cursorForeground": "#a0a0a0cc",
  //"terminalOverviewRuler.findMatchForeground": "#d186167e",
  //"terminalStickyScrollHover.background": "#f0f0f0",
  //"terminalSymbolIcon.aliasForeground": "#652d90",
  //"terminalSymbolIcon.argumentForeground": "#007acc",
  //"terminalSymbolIcon.branchForeground": "#616161",
  //"terminalSymbolIcon.commitForeground": "#616161",
  //"terminalSymbolIcon.fileForeground": "#616161",
  //"terminalSymbolIcon.flagForeground": "#d67e00",
  //"terminalSymbolIcon.folderForeground": "#616161",
  //"terminalSymbolIcon.methodForeground": "#652d90",
  //"terminalSymbolIcon.optionForeground": "#d67e00",
  //"terminalSymbolIcon.optionValueForeground": "#007acc",
  //"terminalSymbolIcon.pullRequestDoneForeground": "#616161",
  //"terminalSymbolIcon.pullRequestForeground": "#616161",
  //"terminalSymbolIcon.remoteForeground": "#616161",
  //"terminalSymbolIcon.stashForeground": "#616161",
  //"terminalSymbolIcon.symbolText": "#616161",
  //"terminalSymbolIcon.symbolicLinkFileForeground": "#616161",
  //"terminalSymbolIcon.symbolicLinkFolderForeground": "#616161",
  //"terminalSymbolIcon.tagForeground": "#616161",
  //"testing.coverCountBadgeBackground": "#ff8c00",
  //"testing.coverCountBadgeForeground": "#000000",
  //"testing.coveredBackground": "#99ffe415",
  //"testing.coveredBorder": "#99ffe410",
  //"testing.coveredGutterBackground": "#99ffe40c",
  //"testing.iconErrored": "#f14c4c",
  //"testing.iconErrored.retired": "#f14c4cb3",
  //"testing.iconFailed": "#f14c4c",
  //"testing.iconFailed.retired": "#f14c4cb3",
  //"testing.iconPassed": "#73c991",
  //"testing.iconPassed.retired": "#73c991b3",
  //"testing.iconQueued": "#cca700",
  //"testing.iconQueued.retired": "#cca700b3",
  //"testing.iconSkipped": "#848484",
  //"testing.iconSkipped.retired": "#848484b3",
  //"testing.iconUnset": "#848484",
  //"testing.iconUnset.retired": "#848484b3",
  //"testing.message.error.badgeBackground": "#e51400",
  //"testing.message.error.badgeBorder": "#e51400",
  //"testing.message.error.badgeForeground": "#ffffff",
  //"testing.message.info.decorationForeground": "#00000080",
  //"testing.messagePeekBorder": "#0063d3",
  //"testing.messagePeekHeaderBackground": "#0063d31a",
  //"testing.peekBorder": "#ff8080",
  //"testing.peekHeaderBackground": "#ff80801a",
  //"testing.runAction": "#73c991",
  //"testing.uncoveredBackground": "#ff808015",
  //"testing.uncoveredBorder": "#ff808010",
  //"testing.uncoveredBranchBackground": "#ffeaea",
  //"testing.uncoveredGutterBackground": "#ff80801f",
  //"textBlockQuote.background": "#f2f2f2",
  //"textBlockQuote.border": "#007acc80",
  //"textCodeBlock.background": "#dcdcdc66",
  //"textPreformat.background": "#0000001a",
  //"textPreformat.foreground": "#a31515",
  //"textSeparator.foreground": "#0000002e",
  //"toolbar.activeBackground": "#a6a6a650",
  //"toolbar.hoverBackground": "#b8b8b850",
  //"tree.inactiveIndentGuidesStroke": "#a9a9a966",
  //"tree.indentGuidesStroke": "#a9a9a9",
  //"tree.tableColumnsBorder": "#61616120",
  //"tree.tableOddRowsBackground": "#6161610a",
  //"walkThrough.embeddedEditorBackground": "#f4f4f4",
  //"walkthrough.stepTitle.foreground": "#000000",
  //"welcomePage.progress.background": "#ffffff",
  //"welcomePage.progress.foreground": "#ff8c00",
  //"welcomePage.tileBackground": "#f5f5f5",
  //"welcomePage.tileBorder": "#0000001a",
  //"welcomePage.tileHoverBackground": "#dddddd",
  //"widget.shadow": "#00000029",
  //"activityBar.activeBackground": null,
  //"activityBar.activeFocusBorder": null,
  //"activityBar.border": null,
  //"activityBarTop.activeBackground": null,
  //"activityBarTop.background": null,
  //"button.border": null,
  //"button.secondaryBorder": null,
  //"contrastActiveBorder": null,
  //"contrastBorder": null,
  //"debugToolBar.border": null,
  //"diffEditor.border": null,
  //"diffEditor.insertedTextBorder": null,
  //"diffEditor.removedTextBorder": null,
  //"diffEditorGutter.insertedLineBackground": null,
  //"diffEditorGutter.removedLineBackground": null,
  //"diffEditorOverview.insertedForeground": null,
  //"diffEditorOverview.removedForeground": null,
  //"dropdown.listBackground": null,
  //"editor.findMatchBorder": null,
  //"editor.findMatchForeground": null,
  //"editor.findMatchHighlightBorder": null,
  //"editor.findMatchHighlightForeground": null,
  //"editor.findRangeHighlightBorder": null,
  //"editor.inactiveLineHighlightBackground": null,
  //"editor.lineHighlightBackground": null,
  //"editor.rangeHighlightBorder": null,
  //"editor.selectionForeground": null,
  //"editor.selectionHighlightBorder": null,
  //"editor.snippetFinalTabstopHighlightBackground": null,
  //"editor.snippetTabstopHighlightBorder": null,
  //"editor.symbolHighlightBorder": null,
  //"editor.wordHighlightBorder": null,
  //"editor.wordHighlightStrongBorder": null,
  //"editor.wordHighlightTextBorder": null,
  //"editorBracketMatch.foreground": null,
  //"editorCursor.background": null,
  //"editorError.background": null,
  //"editorError.border": null,
  //"editorGhostText.background": null,
  //"editorGhostText.border": null,
  //"editorGroup.dropIntoPromptBorder": null,
  //"editorGroup.emptyBackground": null,
  //"editorGroup.focusedEmptyBorder": null,
  //"editorGroupHeader.border": null,
  //"editorGroupHeader.tabsBorder": null,
  //"editorHint.border": null,
  //"editorInfo.background": null,
  //"editorInfo.border": null,
  //"editorLineNumber.dimmedForeground": null,
  //"editorMultiCursor.primary.background": null,
  //"editorMultiCursor.secondary.background": null,
  //"editorOverviewRuler.background": null,
  //"editorStickyScroll.border": null,
  //"editorSuggestWidget.selectedIconForeground": null,
  //"editorUnicodeHighlight.background": null,
  //"editorUnnecessaryCode.border": null,
  //"editorWarning.background": null,
  //"editorWarning.border": null,
  //"editorWidget.resizeBorder": null,
  //"extensionButton.border": null,
  //"gauge.border": null,
  //"gitlens.decorations.branchUnpublishedForegroundColor": null,
  //"gitlens.decorations.branchUpToDateForegroundColor": null,
  //"input.border": null,
  //"inputValidation.errorForeground": null,
  //"inputValidation.infoForeground": null,
  //"inputValidation.warningForeground": null,
  //"list.activeSelectionIconForeground": null,
  //"list.filterMatchBorder": null,
  //"list.focusAndSelectionOutline": null,
  //"list.focusBackground": null,
  //"list.focusForeground": null,
  //"list.hoverForeground": null,
  //"list.inactiveFocusBackground": null,
  //"list.inactiveFocusOutline": null,
  //"list.inactiveSelectionForeground": null,
  //"list.inactiveSelectionIconForeground": null,
  //"menu.border": null,
  //"menu.selectionBorder": null,
  //"menubar.selectionBorder": null,
  //"merge.border": null,
  //"minimap.background": null,
  //"notebook.cellHoverBackground": null,
  //"notebook.focusedCellBackground": null,
  //"notebook.inactiveSelectedCellBorder": null,
  //"notebook.outputContainerBackgroundColor": null,
  //"notebook.outputContainerBorderColor": null,
  //"notificationCenter.border": null,
  //"notificationCenterHeader.foreground": null,
  //"notificationToast.border": null,
  //"outputView.background": null,
  //"outputViewStickyScroll.background": null,
  //"panelSectionHeader.border": null,
  //"panelSectionHeader.foreground": null,
  //"panelStickyScroll.border": null,
  //"panelTitle.border": null,
  //"peekViewEditor.matchHighlightBorder": null,
  //"quickInputList.focusIconForeground": null,
  //"radio.inactiveBackground": null,
  //"radio.inactiveForeground": null,
  //"scrollbar.background": null,
  //"searchEditor.findMatchBorder": null,
  //"searchEditor.textInputBorder": null,
  //"settings.numberInputBorder": null,
  //"settings.textInputBorder": null,
  //"sideBar.border": null,
  //"sideBar.foreground": null,
  //"sideBarActivityBarTop.border": null,
  //"sideBarSectionHeader.border": null,
  //"sideBarStickyScroll.border": null,
  //"sideBarTitle.border": null,
  //"statusBar.border": null,
  //"statusBar.debuggingBorder": null,
  //"statusBar.noFolderBorder": null,
  //"tab.activeBorder": null,
  //"tab.activeBorderTop": null,
  //"tab.hoverBackground": null,
  //"tab.hoverBorder": null,
  //"tab.hoverForeground": null,
  //"tab.selectedBorderTop": null,
  //"tab.unfocusedActiveBorder": null,
  //"tab.unfocusedActiveBorderTop": null,
  //"tab.unfocusedHoverBackground": null,
  //"tab.unfocusedHoverBorder": null,
  //"tab.unfocusedHoverForeground": null,
  //"terminal.background": null,
  //"terminal.findMatchBorder": null,
  //"terminal.findMatchHighlightBorder": null,
  //"terminal.selectionForeground": null,
  //"terminal.tab.activeBorder": null,
  //"terminalCursor.background": null,
  //"terminalCursor.foreground": null,
  //"terminalStickyScroll.background": null,
  //"terminalStickyScroll.border": null,
  //"terminalSymbolIcon.inlineSuggestionForeground": null,
  //"testing.message.error.lineBackground": null,
  //"testing.message.info.lineBackground": null,
  //"textPreformat.border": null,
  //"titleBar.border": null,
  //"toolbar.hoverOutline": null,
  //"welcomePage.background": null,
  //"widget.border": null,
  //"window.activeBorder": null,
  //"window.inactiveBorder": null
};

const _vesperTokenColors = [
  {
    scope: ["comment", "punctuation.definition.comment"],
    settings: {
      foreground: "#8B8B8B",
    },
  },
  {
    scope: ["variable", "string constant.other.placeholder", "entity.name.tag"],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: ["constant.other.color"],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: ["invalid", "invalid.illegal"],
    settings: {
      foreground: "#FF8080",
    },
  },
  {
    scope: ["keyword", "storage.type", "storage.modifier"],
    settings: {
      foreground: "#505050",
    },
  },
  {
    scope: [
      "keyword.control",
      "constant.other.color",
      "punctuation.definition.tag",
      "punctuation.separator.inheritance.php",
      "punctuation.definition.tag.html",
      "punctuation.definition.tag.begin.html",
      "punctuation.definition.tag.end.html",
      "punctuation.section.embedded",
      "keyword.other.template",
      "keyword.other.substitution",
    ],
    settings: {
      foreground: "#505050",
    },
  },
  {
    scope: ["entity.name.tag", "meta.tag.sgml", "markup.deleted.git_gutter"],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "entity.name.function",
      "variable.function",
      "support.function",
      "keyword.other.special-method",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: ["meta.block variable.other"],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: ["support.other.variable", "string.other.link"],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: [
      "constant.numeric",
      "support.constant",
      "constant.character",
      "constant.escape",
      "keyword.other.unit",
      "keyword.other",
      "constant.language.boolean",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "string",
      "constant.other.symbol",
      "constant.other.key",
      "meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js",
    ],
    settings: {
      foreground: "#008080",
    },
  },
  {
    scope: [
      "entity.name",
      "support.type",
      "support.class",
      "support.other.namespace.use.php",
      "meta.use.php",
      "support.other.namespace.php",
      "markup.changed.git_gutter",
      "support.type.sys-types",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "source.css support.type.property-name",
      "source.sass support.type.property-name",
      "source.scss support.type.property-name",
      "source.less support.type.property-name",
      "source.stylus support.type.property-name",
      "source.postcss support.type.property-name",
      "support.type.vendored.property-name.css",
      "source.css.scss entity.name.tag",
      "variable.parameter.keyframe-list.css",
      "meta.property-name.css",
      "variable.parameter.url.scss",
      "meta.property-value.scss",
      "meta.property-value.css",
    ],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: [
      "entity.name.module.js",
      "variable.import.parameter.js",
      "variable.other.class.js",
    ],
    settings: {
      foreground: "#FF8080",
    },
  },
  {
    scope: ["variable.language"],
    settings: {
      foreground: "#505050",
    },
  },
  {
    scope: ["entity.name.method.js"],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: [
      "meta.class-method.js entity.name.function.js",
      "variable.function.constructor",
    ],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: [
      "entity.other.attribute-name",
      "meta.property-list.scss",
      "meta.attribute-selector.scss",
      "meta.property-value.css",
      "entity.other.keyframe-offset.css",
      "meta.selector.css",
      "entity.name.tag.reference.scss",
      "entity.name.tag.nesting.css",
      "punctuation.separator.key-value.css",
    ],
    settings: {
      foreground: "#505050",
    },
  },
  {
    scope: [
      "text.html.basic entity.other.attribute-name.html",
      "text.html.basic entity.other.attribute-name",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "entity.other.attribute-name.class",
      "entity.other.attribute-name.id",
      "meta.attribute-selector.scss",
      "variable.parameter.misc.css",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: ["source.sass keyword.control", "meta.attribute-selector.scss"],
    settings: {
      foreground: "#008080",
    },
  },
  {
    scope: ["markup.inserted"],
    settings: {
      foreground: "#008080",
    },
  },
  {
    scope: ["markup.deleted"],
    settings: {
      foreground: "#FF8080",
    },
  },
  {
    scope: ["markup.changed"],
    settings: {
      foreground: "#505050",
    },
  },
  {
    scope: ["string.regexp"],
    settings: {
      foreground: "#505050",
    },
  },
  {
    scope: ["constant.character.escape"],
    settings: {
      foreground: "#505050",
    },
  },
  {
    scope: ["*url*", "*link*", "*uri*"],
    settings: {
      fontStyle: "underline",
    },
  },
  {
    scope: [
      "tag.decorator.js entity.name.tag.js",
      "tag.decorator.js punctuation.definition.tag.js",
    ],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: ["source.js constant.other.object.key.js string.unquoted.label.js"],
    settings: {
      foreground: "#FF8080",
      fontStyle: "italic",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: [
      "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: ["text.html.markdown", "punctuation.definition.list_item.markdown"],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: ["text.html.markdown markup.inline.raw.markdown"],
    settings: {
      foreground: "#505050",
    },
  },
  {
    scope: [
      "text.html.markdown markup.inline.raw.markdown punctuation.definition.raw.markdown",
    ],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: [
      "markdown.heading",
      "markup.heading | markup.heading entity.name",
      "markup.heading.markdown punctuation.definition.heading.markdown",
      "markup.heading",
      "markup.inserted.git_gutter",
    ],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: ["markup.italic"],
    settings: {
      foreground: "#000000",
      fontStyle: "italic",
    },
  },
  {
    scope: ["markup.bold", "markup.bold string"],
    settings: {
      foreground: "#000000",
      fontStyle: "bold",
    },
  },
  {
    scope: [
      "markup.bold markup.italic",
      "markup.italic markup.bold",
      "markup.quote markup.bold",
      "markup.bold markup.italic string",
      "markup.italic markup.bold string",
      "markup.quote markup.bold string",
    ],
    settings: {
      foreground: "#000000",
      fontStyle: "bold",
    },
  },
  {
    scope: ["markup.underline"],
    settings: {
      foreground: "#FF8C00",
      fontStyle: "underline",
    },
  },
  {
    scope: ["markup.quote punctuation.definition.blockquote.markdown"],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: ["markup.quote"],
    settings: {},
  },
  {
    scope: ["string.other.link.title.markdown"],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: ["string.other.link.description.title.markdown"],
    settings: {
      foreground: "#505050",
    },
  },
  {
    scope: ["constant.other.reference.link.markdown"],
    settings: {
      foreground: "#FF8C00",
    },
  },
  {
    scope: ["markup.raw.block"],
    settings: {
      foreground: "#505050",
    },
  },
  {
    scope: ["markup.raw.block.fenced.markdown"],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: ["punctuation.definition.fenced.markdown"],
    settings: {
      foreground: "#A0A0A0",
    },
  },
  {
    scope: [
      "markup.raw.block.fenced.markdown",
      "variable.language.fenced.markdown",
      "punctuation.section.class.end",
    ],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: ["variable.language.fenced.markdown"],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: ["meta.separator"],
    settings: {
      foreground: "#65737E",
      fontStyle: "bold",
    },
  },
  {
    scope: ["markup.table"],
    settings: {
      foreground: "#000000",
    },
  },
  {
    scope: "token.info-token",
    settings: {
      foreground: "#316BCD",
    },
  },
  {
    scope: "token.warn-token",
    settings: {
      foreground: "#CD9731",
    },
  },
  {
    scope: "token.error-token",
    settings: {
      foreground: "#CD3131",
    },
  },
  {
    scope: "token.debug-token",
    settings: {
      foreground: "#800080",
    },
  },
];

const tokenColorsToRules = (
  tokenColors: typeof vesperTokenColors,
): { token: string; foreground?: string; fontStyle?: string }[] => {
  const rules: Map<string, { foreground?: string; fontStyle?: string }> =
    new Map();

  tokenColors.forEach((entry) => {
    const scopes = Array.isArray(entry.scope) ? entry.scope : [entry.scope];
    const foreground = entry.settings.foreground
      ? entry.settings.foreground.replace("#", "").toLowerCase()
      : undefined;
    const fontStyle = entry.settings.fontStyle;

    scopes.forEach((scope) => {
      // Map common TextMate scopes to Monaco tokens
      const monacoMappings: Record<string, string[]> = {
        comment: ["comment"],
        string: ["string"],
        keyword: ["keyword"],
        variable: ["variable", "identifier"], // ✅ Key fix
        "variable.language": ["variable.predefined"],
        "variable.parameter": ["variable.parameter"],
        "variable.other": ["variable.other"],
        "entity.name.function": ["identifier.function", "function"],
        "entity.name.type": ["type", "type.identifier"],
        "entity.name.tag": ["tag"],
        "constant.numeric": ["number"],
        "constant.language.boolean": ["keyword.boolean"],
        "storage.type": ["keyword.type"],
        "support.type": ["type"],
        "support.class": ["type.class"],
        "support.function": ["support.function"],
      };

      // Check for exact match first
      const tokens = monacoMappings[scope] || [scope];

      tokens.forEach((token) => {
        if (!rules.has(token)) {
          rules.set(token, { foreground, fontStyle });
        }
      });

      // Also add the full scope as-is (Monaco might support it)
      if (!rules.has(scope)) {
        rules.set(scope, { foreground, fontStyle });
      }
    });
  });

  return Array.from(rules.entries()).map(([token, settings]) => ({
    token,
    ...settings,
  }));
};

function MonacoTestDiff() {
  const handleBeforeMount = (monaco: Monaco) => {
    monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions({
      diagnosticCodesToIgnore: [1, 2, 3, 4, 5, 6, 7], // Ignore all
    });

    monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions({
      noSemanticValidation: true,
      noSyntaxValidation: true,
      noSuggestionDiagnostics: true,
    });

    monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
      noSemanticValidation: true,
      noSyntaxValidation: true,
      noSuggestionDiagnostics: true,
    });

    monaco.editor.defineTheme("vesper-light", {
      base: "vs-dark",
      inherit: true,
      colors: vesperThemeColors,
      rules: tokenColorsToRules(vesperTokenColors),
    });
  };

  const handleMount = (_editor: unknown, monaco: Monaco) => {
    monaco.editor.setTheme("vesper-light");
  };

  return (
    <div style={{ height: "100vh", width: "100%" }}>
      <DiffEditor
        theme="vesper-light"
        beforeMount={handleBeforeMount}
        onMount={handleMount}
        original={oldCode}
        modified={newCode}
        language="typescript"
        options={{
          renderIndicators: false,
          lineDecorationsWidth: 10,
          glyphMargin: false,
          renderSideBySide: true,
          enableSplitViewResizing: true,
          diffAlgorithm: "advanced",
          readOnly: false,
          originalEditable: false,
          // TODO: disable typescript error checking
          experimental: {
            showMoves: true,
          },
        }}
      />
    </div>
  );
}

export default MonacoTestDiff;

// !!!!!!!!!!!!!!!!!!!

async function loadVSCodeTheme(monaco: Monaco) {
  // Load the actual Vesper theme JSON (exported from VS Code)
  const vesperTheme = await fetch("/vesper-theme.json").then((r) => r.json());

  // Convert and register
  monaco.editor.defineTheme("vesper", {
    base: "vs-dark",
    inherit: true,
    colors: vesperTheme.colors,
    rules: convertTokenColors(vesperTheme.tokenColors),
  });
}

function convertTokenColors(tokenColors: any[]) {
  return tokenColors.flatMap((entry) => {
    const scopes = Array.isArray(entry.scope) ? entry.scope : [entry.scope];
    return scopes.map((scope) => ({
      token: scope,
      foreground: entry.settings.foreground?.replace("#", ""),
      background: entry.settings.background?.replace("#", ""),
      fontStyle: entry.settings.fontStyle,
    }));
  });
}
