/**
 * Auto-generated command bindings for Tauri commands
 * Generated by tauri-typegen v0.3.2
 * Generated at: 2025-11-24T14:50:10Z
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';

import { ZodError } from 'zod';
import * as types from './types';

export interface CommandHooks<T> {
  /** Called when Zod schema validation fails */
  onValidationError?: (error: ZodError) => void;

  /** Called when Tauri invoke fails (Rust error, serialization, etc.) */
  onInvokeError?: (error: unknown) => void;

  /** Called when command succeeds */
  onSuccess?: (result: T) => void;

  /** Called after command settles (success or error) */
  onSettled?: () => void;
}

export async function startWatching(params: types.StartWatchingParams, hooks?: CommandHooks<types.StartWatchingResponse>): Promise<types.StartWatchingResponse> {
  try {
    const result = types.StartWatchingParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.StartWatchingResponse>('start_watching', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function stopWatching(params: types.StopWatchingParams, hooks?: CommandHooks<types.StopWatchingResponse>): Promise<types.StopWatchingResponse> {
  try {
    const result = types.StopWatchingParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.StopWatchingResponse>('stop_watching', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getWatcherState(params: types.GetWatcherStateParams, hooks?: CommandHooks<types.WatcherStateInfo>): Promise<types.WatcherStateInfo> {
  try {
    const result = types.GetWatcherStateParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.WatcherStateInfo>('get_watcher_state', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function rescanRepository(params: types.RescanRepositoryParams, hooks?: CommandHooks<types.RescanResponse>): Promise<types.RescanResponse> {
  try {
    const result = types.RescanRepositoryParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.RescanResponse>('rescan_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function currentBranch(params: types.CurrentBranchParams, hooks?: CommandHooks<types.Branch>): Promise<types.Branch> {
  try {
    const result = types.CurrentBranchParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.Branch>('current_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function listBranch(params: types.ListBranchParams, hooks?: CommandHooks<types.Branch[]>): Promise<types.Branch[]> {
  try {
    const result = types.ListBranchParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.Branch[]>('list_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function switchBranch(params: types.SwitchBranchParams, hooks?: CommandHooks<types.GitResult>): Promise<types.GitResult> {
  try {
    const result = types.SwitchBranchParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.GitResult>('switch_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getDiff(params: types.GetDiffParams, hooks?: CommandHooks<types.GetDiffResponse>): Promise<types.GetDiffResponse> {
  try {
    const result = types.GetDiffParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.GetDiffResponse>('get_diff', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function history(params: types.HistoryParams, hooks?: CommandHooks<types.CommitInfo[]>): Promise<types.CommitInfo[]> {
  try {
    const result = types.HistoryParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.CommitInfo[]>('history', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getStatus(params: types.GetStatusParams, hooks?: CommandHooks<types.GetStatusResponse>): Promise<types.GetStatusResponse> {
  try {
    const result = types.GetStatusParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.GetStatusResponse>('get_status', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitAdd(params: types.GitAddParams, hooks?: CommandHooks<types.GitResult>): Promise<types.GitResult> {
  try {
    const result = types.GitAddParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.GitResult>('git_add', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitRemove(params: types.GitRemoveParams, hooks?: CommandHooks<types.GitResult>): Promise<types.GitResult> {
  try {
    const result = types.GitRemoveParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.GitResult>('git_remove', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitDiscard(params: types.GitDiscardParams, hooks?: CommandHooks<types.GitResult>): Promise<types.GitResult> {
  try {
    const result = types.GitDiscardParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.GitResult>('git_discard', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function commit(params: types.CommitParams, hooks?: CommandHooks<types.CommitResult>): Promise<types.CommitResult> {
  try {
    const result = types.CommitParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.CommitResult>('commit', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function generate(hooks?: CommandHooks<types.FileStatus>): Promise<types.FileStatus> {
  try {
    const data = await invoke<types.FileStatus>('_generate');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function addLocalGitRepo(params: types.AddLocalGitRepoParams, hooks?: CommandHooks<types.GitRepoResponse>): Promise<types.GitRepoResponse> {
  try {
    const result = types.AddLocalGitRepoParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.GitRepoResponse>('add_local_git_repo', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function exportType(params: types.ExportTypeParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.ExportTypeParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<void>('export_type', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

