/**
 * Auto-generated TypeScript types for Tauri commands
 * Generated by tauri-plugin-typegen
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from "zod";

export const FileStatusSchema = z.object({
	path: z.string(),
	status: z.string(),
});
export const GetStatusResponseSchema = z.object({
	files: z.array(FileStatusSchema),
});

export const AddParamsSchema = z.object({
	a: z.number(),
	b: z.number(),
});

export const GetStatusParamsSchema = z.object({
	repo_path: z.string(),
});

export const GetStatusSingleFileParamsSchema = z.object({
	repo_path: z.string(),
	file_path: z.string(),
});

export type AddParams = z.infer<typeof AddParamsSchema>;

export type GetStatusParams = z.infer<typeof GetStatusParamsSchema>;

export type GetStatusSingleFileParams = z.infer<
	typeof GetStatusSingleFileParamsSchema
>;

export type GetStatusResponse = z.infer<typeof GetStatusResponseSchema>;

export type FileStatus = z.infer<typeof FileStatusSchema>;
