/**
 * Auto-generated TypeScript types for Tauri commands
 * Generated by tauri-typegen v0.3.2
 * Generated at: 2025-11-24T14:50:10Z
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';


export const FileStatusKindSchema = z.enum(["IndexNew", "IndexModified", "IndexDeleted", "IndexRenamed", "IndexTypechange", "WorktreeNew", "WorktreeModified", "WorktreeDeleted", "WorktreeRenamed", "WorktreeTypechange", "WorktreeUnreadable"]);

export const RepoSitoryStoreSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  origin: z.string().optional(),
  branch: z.string().optional(),
});

export const GitRepoResponseSchema = z.object({
  error: z.string().optional(),
  success: RepoSitoryStoreSchema.optional(),
});

export const FileStatusSchema = z.object({
  path: z.string(),
  new_path: z.string().optional(),
  status: z.array(FileStatusKindSchema),
});

export const WatcherConfigSchema = z.object({
  debounce_ms: z.number(),
  batch_size: z.number(),
  batch_timeout_ms: z.number(),
  max_queue_size: z.number(),
  follow_symlinks: z.boolean(),
  extra_ignores: z.array(z.string()),
  emit_stats: z.boolean(),
  stats_interval_secs: z.number(),
});

export const FileVersionSchema = z.object({
  content: z.string(),
  encoding: z.string().optional(),
  is_binary: z.boolean(),
  byte_length: z.number(),
});

export const GetDiffResponseSchema = z.object({
  file_path: z.string(),
  head: FileVersionSchema.optional(),
  workdir: FileVersionSchema.optional(),
});

export const AuthorSchema = z.object({
  name: z.string(),
  email: z.string(),
});

export const CommitAuthorsSchema = z.object({
  author: AuthorSchema,
  committer: AuthorSchema,
  co_authors: z.array(AuthorSchema),
});

export const CommitInfoSchema = z.object({
  id: z.string(),
  summary: z.string(),
  body: z.string(),
  timestamp: z.number(),
  authors: CommitAuthorsSchema,
});

export const StartWatchingResponseSchema = z.object({
  success: z.boolean(),
  watcher_id: z.string(),
  error: z.string().optional(),
});

export const WatcherStateInfoSchema = z.object({
  is_active: z.boolean(),
  repo_path: z.string(),
  uptime_seconds: z.number(),
});

export const GetStatusResponseSchema = z.object({
  files: z.array(FileStatusSchema),
});

export const CommitResultSchema = z.object({
  success: z.boolean(),
  message: z.string().optional(),
});

export const RescanResponseSchema = z.object({
  success: z.boolean(),
  files_found: z.number(),
  error: z.string().optional(),
});

export const BranchSchema = z.object({
  name: z.string(),
  display_name: z.string(),
  is_remote: z.boolean(),
});

export const StopWatchingResponseSchema = z.object({
  success: z.boolean(),
  error: z.string().optional(),
});

export const GitResultSchema = z.object({
  success: z.boolean(),
  message: z.string().optional(),
});

export const StartWatchingParamsSchema = z.object({
  repoPath: z.string(),
  config: WatcherConfigSchema.optional(),
});

export const StopWatchingParamsSchema = z.object({
  watcherId: z.string(),
});

export const GetWatcherStateParamsSchema = z.object({
  watcherId: z.string(),
});

export const RescanRepositoryParamsSchema = z.object({
  watcherId: z.string(),
});

export const CurrentBranchParamsSchema = z.object({
  repoPath: z.string(),
});

export const ListBranchParamsSchema = z.object({
  repoPath: z.string(),
});

export const SwitchBranchParamsSchema = z.object({
  repoPath: z.string(),
  branchName: z.string(),
});

export const GetDiffParamsSchema = z.object({
  repoPath: z.string(),
  filePath: z.string(),
});

export const HistoryParamsSchema = z.object({
  repoPath: z.string(),
  skip: z.number(),
  limit: z.number(),
});

export const GetStatusParamsSchema = z.object({
  repoPath: z.string(),
});

export const GitAddParamsSchema = z.object({
  repoPath: z.string(),
  file: z.string(),
});

export const GitRemoveParamsSchema = z.object({
  repoPath: z.string(),
  file: z.string(),
});

export const GitDiscardParamsSchema = z.object({
  repoPath: z.string(),
  file: z.string(),
});

export const CommitParamsSchema = z.object({
  repoPath: z.string(),
  message: z.string(),
  description: z.string().optional(),
  coAuthors: z.array(z.string()).optional(),
});

export const AddLocalGitRepoParamsSchema = z.object({
  repoPath: z.string(),
});

export const ExportTypeParamsSchema = z.object({
  a: RepoSitoryStoreSchema,
});

export type StartWatchingParams = z.infer<typeof StartWatchingParamsSchema>;

export type StopWatchingParams = z.infer<typeof StopWatchingParamsSchema>;

export type GetWatcherStateParams = z.infer<typeof GetWatcherStateParamsSchema>;

export type RescanRepositoryParams = z.infer<typeof RescanRepositoryParamsSchema>;

export type CurrentBranchParams = z.infer<typeof CurrentBranchParamsSchema>;

export type ListBranchParams = z.infer<typeof ListBranchParamsSchema>;

export type SwitchBranchParams = z.infer<typeof SwitchBranchParamsSchema>;

export type GetDiffParams = z.infer<typeof GetDiffParamsSchema>;

export type HistoryParams = z.infer<typeof HistoryParamsSchema>;

export type GetStatusParams = z.infer<typeof GetStatusParamsSchema>;

export type GitAddParams = z.infer<typeof GitAddParamsSchema>;

export type GitRemoveParams = z.infer<typeof GitRemoveParamsSchema>;

export type GitDiscardParams = z.infer<typeof GitDiscardParamsSchema>;

export type CommitParams = z.infer<typeof CommitParamsSchema>;

export type AddLocalGitRepoParams = z.infer<typeof AddLocalGitRepoParamsSchema>;

export type ExportTypeParams = z.infer<typeof ExportTypeParamsSchema>;

export type RescanResponse = z.infer<typeof RescanResponseSchema>;

export type FileStatus = z.infer<typeof FileStatusSchema>;

export type CommitInfo = z.infer<typeof CommitInfoSchema>;

export type RepoSitoryStore = z.infer<typeof RepoSitoryStoreSchema>;

export type FileStatusKind = z.infer<typeof FileStatusKindSchema>;

export type CommitAuthors = z.infer<typeof CommitAuthorsSchema>;

export type GetDiffResponse = z.infer<typeof GetDiffResponseSchema>;

export type GitRepoResponse = z.infer<typeof GitRepoResponseSchema>;

export type GetStatusResponse = z.infer<typeof GetStatusResponseSchema>;

export type GitResult = z.infer<typeof GitResultSchema>;

export type WatcherConfig = z.infer<typeof WatcherConfigSchema>;

export type FileVersion = z.infer<typeof FileVersionSchema>;

export type CommitResult = z.infer<typeof CommitResultSchema>;

export type Branch = z.infer<typeof BranchSchema>;

export type Author = z.infer<typeof AuthorSchema>;

export type StopWatchingResponse = z.infer<typeof StopWatchingResponseSchema>;

export type StartWatchingResponse = z.infer<typeof StartWatchingResponseSchema>;

export type WatcherStateInfo = z.infer<typeof WatcherStateInfoSchema>;

