/**
 * Auto-generated TypeScript types for Tauri commands
 * Generated by tauri-typegen v0.3.2
 * Generated at: 2025-12-27T10:34:55Z
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';


export const AuthorSchema = z.object({
  name: z.string(),
  email: z.string(),
});

export const FileStatusKindSchema = z.enum(["IndexNew", "IndexModified", "IndexDeleted", "IndexRenamed", "IndexTypechange", "WorktreeNew", "WorktreeModified", "WorktreeDeleted", "WorktreeRenamed", "WorktreeTypechange", "WorktreeUnreadable"]);

export const RepoSitoryStoreSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  origin: z.string().optional(),
  branch: z.string().optional(),
});

export const GitRepoResponseSchema = z.object({
  error: z.string().optional(),
  success: RepoSitoryStoreSchema.optional(),
});

export const FileStatusSchema = z.object({
  path: z.string(),
  new_path: z.string().optional(),
  status: z.array(FileStatusKindSchema),
});

export const GetStatusResponseSchema = z.object({
  files: z.array(FileStatusSchema),
});

export const CommitAuthorsSchema = z.object({
  author: AuthorSchema,
  committer: AuthorSchema,
  co_authors: z.array(AuthorSchema),
});

export const CommitInfoSchema = z.object({
  id: z.string(),
  summary: z.string(),
  body: z.string(),
  timestamp: z.number(),
  authors: CommitAuthorsSchema,
});

export const RepositoryOriginSchema = z.object({
  remote_name: z.string(),
  remote_url: z.string(),
  host: z.string().optional(),
  provider: z.string().optional(),
  owner: z.string().optional(),
  repo: z.string().optional(),
  protocol: z.string(),
});

export const CommitStatsSchema = z.object({
  insertions: z.number(),
  deletions: z.number(),
  files_changed: z.number(),
});

export const FileVersionSchema = z.object({
  content: z.string(),
  encoding: z.string().optional(),
  is_binary: z.boolean(),
  byte_length: z.number(),
});

export const GetDiffResponseSchema = z.object({
  file_path: z.string(),
  head: FileVersionSchema.optional(),
  workdir: FileVersionSchema.optional(),
  patch: z.string().optional(),
});

export const CommitResultSchema = z.object({
  success: z.boolean(),
  message: z.string().optional(),
});

export const BranchSchema = z.object({
  name: z.string(),
  display_name: z.string(),
  is_remote: z.boolean(),
});

export const FullCommitInfoSchema = z.object({
  id: z.string(),
  timestamp: z.number(),
  summary: z.string(),
  body: z.string(),
  authors: CommitAuthorsSchema,
  stats: CommitStatsSchema,
});

export const GitResultSchema = z.object({
  success: z.boolean(),
  message: z.string().optional(),
});

export const GetStatusParamsSchema = z.object({
  repoPath: z.string(),
});

export const GitAddParamsSchema = z.object({
  repoPath: z.string(),
  file: z.string(),
});

export const GitRemoveParamsSchema = z.object({
  repoPath: z.string(),
  file: z.string(),
});

export const GitDiscardParamsSchema = z.object({
  repoPath: z.string(),
  file: z.string(),
});

export const CommitParamsSchema = z.object({
  repoPath: z.string(),
  message: z.string(),
  description: z.string().optional(),
  coAuthors: z.array(z.string()).optional(),
});

export const GetDiffParamsSchema = z.object({
  repoPath: z.string(),
  filePath: z.string(),
});

export const RepositoryOriginParamsSchema = z.object({
  repoPath: z.string(),
});

export const AddLocalGitRepoParamsSchema = z.object({
  repoPath: z.string(),
});

export const ExportTypeParamsSchema = z.object({
  a: RepoSitoryStoreSchema,
});

export const HistoryParamsSchema = z.object({
  repoPath: z.string(),
  skip: z.number(),
  limit: z.number(),
});

export const LastCommitParamsSchema = z.object({
  repoPath: z.string(),
});

export const CommitByIdParamsSchema = z.object({
  repoPath: z.string(),
  hash: z.string(),
});

export const CurrentBranchParamsSchema = z.object({
  repoPath: z.string(),
});

export const ListBranchParamsSchema = z.object({
  repoPath: z.string(),
});

export const SwitchBranchParamsSchema = z.object({
  repoPath: z.string(),
  branchName: z.string(),
});

export type GetStatusParams = z.infer<typeof GetStatusParamsSchema>;

export type GitAddParams = z.infer<typeof GitAddParamsSchema>;

export type GitRemoveParams = z.infer<typeof GitRemoveParamsSchema>;

export type GitDiscardParams = z.infer<typeof GitDiscardParamsSchema>;

export type CommitParams = z.infer<typeof CommitParamsSchema>;

export type GetDiffParams = z.infer<typeof GetDiffParamsSchema>;

export type RepositoryOriginParams = z.infer<typeof RepositoryOriginParamsSchema>;

export type AddLocalGitRepoParams = z.infer<typeof AddLocalGitRepoParamsSchema>;

export type ExportTypeParams = z.infer<typeof ExportTypeParamsSchema>;

export type HistoryParams = z.infer<typeof HistoryParamsSchema>;

export type LastCommitParams = z.infer<typeof LastCommitParamsSchema>;

export type CommitByIdParams = z.infer<typeof CommitByIdParamsSchema>;

export type CurrentBranchParams = z.infer<typeof CurrentBranchParamsSchema>;

export type ListBranchParams = z.infer<typeof ListBranchParamsSchema>;

export type SwitchBranchParams = z.infer<typeof SwitchBranchParamsSchema>;

export type RepoSitoryStore = z.infer<typeof RepoSitoryStoreSchema>;

export type FileStatusKind = z.infer<typeof FileStatusKindSchema>;

export type CommitStats = z.infer<typeof CommitStatsSchema>;

export type GetStatusResponse = z.infer<typeof GetStatusResponseSchema>;

export type Branch = z.infer<typeof BranchSchema>;

export type CommitResult = z.infer<typeof CommitResultSchema>;

export type CommitAuthors = z.infer<typeof CommitAuthorsSchema>;

export type Author = z.infer<typeof AuthorSchema>;

export type GitResult = z.infer<typeof GitResultSchema>;

export type CommitInfo = z.infer<typeof CommitInfoSchema>;

export type FileVersion = z.infer<typeof FileVersionSchema>;

export type RepositoryOrigin = z.infer<typeof RepositoryOriginSchema>;

export type GitRepoResponse = z.infer<typeof GitRepoResponseSchema>;

export type FullCommitInfo = z.infer<typeof FullCommitInfoSchema>;

export type GetDiffResponse = z.infer<typeof GetDiffResponseSchema>;

export type FileStatus = z.infer<typeof FileStatusSchema>;

