import { createHash } from "node:crypto";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, resolve } from "node:path";
import { cefBinaryVersionFromCargoLock } from "./cef-lockfile";

const desktopDirectory = resolve(import.meta.dirname, "..");
const repositoryRoot = resolve(desktopDirectory, "../..");
const noticeDirectory = resolve(desktopDirectory, "src-tauri/resources/cef");
const cefLicense = resolve(noticeDirectory, "LICENSE.txt");
const chromiumCredits = resolve(noticeDirectory, "LICENSES.chromium.html");

function fail(message: string): never {
  throw new Error(`Cannot prepare CEF redistribution notices: ${message}`);
}

function normalizedPlatform(): string {
  const platform = process.env.TAURI_ENV_PLATFORM ?? process.platform;
  if (platform === "darwin" || platform === "macos") return "macos";
  if (platform === "win32" || platform === "windows") return "windows";
  if (platform === "linux") return "linux";
  return fail(`unsupported platform ${platform}`);
}

function normalizedArchitecture(): string {
  const architecture = process.env.TAURI_ENV_ARCH ?? process.arch;
  if (architecture === "arm64" || architecture === "aarch64") {
    return "aarch64";
  }
  if (architecture === "x64" || architecture === "x86_64") {
    return "x86_64";
  }
  if (architecture === "ia32" || architecture === "i686") return "x86";
  if (architecture === "arm") return "arm";
  return fail(`unsupported architecture ${architecture}`);
}

function defaultCefCache(platform: string): string {
  if (platform === "windows") {
    const localAppData = process.env.LOCALAPPDATA;
    if (!localAppData) return fail("LOCALAPPDATA is not set");
    return resolve(localAppData, "tauri-cef");
  }

  const xdgCache = process.env.XDG_CACHE_HOME;
  if (platform === "linux" && xdgCache) {
    return resolve(xdgCache, "tauri-cef");
  }
  if (platform === "macos") {
    return resolve(homedir(), "Library/Caches/tauri-cef");
  }
  return resolve(homedir(), ".cache/tauri-cef");
}

function cefBinaryVersion(): string {
  const cargoLock = readFileSync(resolve(repositoryRoot, "Cargo.lock"), "utf8");
  try {
    return cefBinaryVersionFromCargoLock(cargoLock);
  } catch (error) {
    return fail(
      error instanceof Error ? error.message : "cannot parse Cargo.lock",
    );
  }
}

function resolveCreditsSource(): string {
  const platform = normalizedPlatform();
  const architecture = normalizedArchitecture();
  const cacheOrDistribution = resolve(
    process.env.CEF_PATH ?? defaultCefCache(platform),
  );
  const directCredits = resolve(cacheOrDistribution, "CREDITS.html");
  if (existsSync(directCredits)) return directCredits;

  const cachedCredits = resolve(
    cacheOrDistribution,
    cefBinaryVersion(),
    `cef_${platform}_${architecture}`,
    "CREDITS.html",
  );
  if (existsSync(cachedCredits)) return cachedCredits;

  return fail(
    `CREDITS.html is missing from ${cacheOrDistribution}; run the CEF Cargo build before the bundle hook`,
  );
}

const licenseText = readFileSync(cefLicense, "utf8");
const normalizedLicenseText = licenseText
  .replace(/^\/\/\s?/gm, "")
  .replace(/\s+/g, " ");
if (
  !normalizedLicenseText.includes("Chromium Embedded Framework") ||
  !normalizedLicenseText.includes("Redistributions in binary form")
) {
  fail(`${cefLicense} is not the expected CEF BSD license`);
}

const creditsSource = resolveCreditsSource();
if (statSync(creditsSource).size < 100_000) {
  fail(`${creditsSource} is too small to be Chromium's generated credits`);
}
const creditsText = readFileSync(creditsSource, "utf8");
if (
  !creditsText.includes("Generated by licenses.py") ||
  !creditsText.includes("Chromium software is made available as source code")
) {
  fail(`${creditsSource} is not Chromium's generated credits document`);
}

mkdirSync(dirname(chromiumCredits), { recursive: true });
copyFileSync(creditsSource, chromiumCredits);

const sourceHash = createHash("sha256").update(creditsText).digest("hex");
const copiedHash = createHash("sha256")
  .update(readFileSync(chromiumCredits))
  .digest("hex");
if (sourceHash !== copiedHash) fail("copied Chromium credits checksum changed");

console.log(
  `Prepared CEF notices from ${creditsSource} (sha256 ${sourceHash}).`,
);
