-- Authored temporary identities are never foreign keyed to evictable repository cache.
CREATE TABLE pull_drafts(account_id TEXT NOT NULL,draft_id TEXT NOT NULL CHECK(length(draft_id)=36),repository_id TEXT NOT NULL CHECK(octet_length(repository_id) BETWEEN 1 AND 1024),title TEXT NOT NULL CHECK(octet_length(title)<=1024),body TEXT NOT NULL CHECK(octet_length(body)<=16384),source_branch TEXT NOT NULL CHECK(octet_length(source_branch)<=1024),base_branch TEXT NOT NULL CHECK(octet_length(base_branch)<=1024),local_repository_id TEXT NOT NULL CHECK(octet_length(local_repository_id)<=1024),link_id TEXT NOT NULL CHECK(octet_length(link_id)<=1024),link_generation TEXT NOT NULL CHECK(octet_length(link_generation)<=1024),is_draft INTEGER NOT NULL CHECK(is_draft IN (0,1)),generation INTEGER NOT NULL CHECK(generation>0),PRIMARY KEY(account_id,draft_id),FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT) STRICT;
CREATE TRIGGER pull_draft_identity BEFORE UPDATE OF account_id,draft_id,repository_id ON pull_drafts BEGIN SELECT RAISE(ABORT,'immutable pull draft identity'); END;
CREATE TRIGGER pull_draft_retained BEFORE DELETE ON pull_drafts BEGIN SELECT RAISE(ABORT,'pull drafts require explicit retention'); END;
CREATE TABLE pull_submissions(account_id TEXT NOT NULL,draft_id TEXT NOT NULL,draft_generation INTEGER NOT NULL CHECK(draft_generation>0),command_id TEXT NOT NULL,submission_hash BLOB NOT NULL CHECK(typeof(submission_hash)='blob' AND length(submission_hash)=32),content_hash BLOB NOT NULL CHECK(typeof(content_hash)='blob' AND length(content_hash)=32),PRIMARY KEY(account_id,draft_id,draft_generation),UNIQUE(account_id,command_id),FOREIGN KEY(account_id,draft_id) REFERENCES pull_drafts(account_id,draft_id) ON DELETE RESTRICT,FOREIGN KEY(account_id,command_id,submission_hash) REFERENCES commands(account_id,command_id,submission_hash) ON DELETE RESTRICT) STRICT;
CREATE TRIGGER pull_submission_bound BEFORE INSERT ON pull_submissions WHEN NOT EXISTS(SELECT 1 FROM pull_drafts d JOIN commands c ON c.account_id=d.account_id WHERE d.account_id=NEW.account_id AND d.draft_id=NEW.draft_id AND d.generation=NEW.draft_generation AND c.command_id=NEW.command_id AND c.target_id=d.repository_id AND c.target_kind='repository' AND c.operation_kind='github.create_pull_request' AND c.payload_version=1 AND c.state='queued') BEGIN SELECT RAISE(ABORT,'invalid pull submission binding'); END;
CREATE TRIGGER pull_submission_immutable BEFORE UPDATE ON pull_submissions BEGIN SELECT RAISE(ABORT,'immutable pull submission'); END;
CREATE TRIGGER pull_submission_retained BEFORE DELETE ON pull_submissions BEGIN SELECT RAISE(ABORT,'pull submissions require explicit retention'); END;
CREATE INDEX pull_submissions_history ON pull_submissions(account_id,draft_id,draft_generation DESC);
CREATE TABLE pull_resolutions(account_id TEXT NOT NULL,draft_id TEXT NOT NULL,command_id TEXT NOT NULL,entity_id TEXT NOT NULL,provider_id TEXT NOT NULL,number TEXT NOT NULL,url TEXT NOT NULL,observed_source_oid TEXT NOT NULL CHECK(length(observed_source_oid)=40 AND observed_source_oid NOT GLOB '*[^0-9a-f]*'),observed_base_oid TEXT NOT NULL CHECK(length(observed_base_oid)=40 AND observed_base_oid NOT GLOB '*[^0-9a-f]*'),PRIMARY KEY(account_id,draft_id),UNIQUE(account_id,command_id),UNIQUE(account_id,provider_id),FOREIGN KEY(account_id,draft_id) REFERENCES pull_drafts(account_id,draft_id) ON DELETE RESTRICT,FOREIGN KEY(account_id,command_id) REFERENCES pull_submissions(account_id,command_id) ON DELETE RESTRICT) STRICT;
CREATE TRIGGER pull_resolution_bound BEFORE INSERT ON pull_resolutions WHEN NOT EXISTS(SELECT 1 FROM pull_submissions s WHERE s.account_id=NEW.account_id AND s.draft_id=NEW.draft_id AND s.command_id=NEW.command_id) BEGIN SELECT RAISE(ABORT,'invalid pull resolution binding'); END;
CREATE TRIGGER pull_resolution_immutable BEFORE UPDATE ON pull_resolutions BEGIN SELECT RAISE(ABORT,'immutable pull resolution'); END;
CREATE TRIGGER pull_resolution_retained BEFORE DELETE ON pull_resolutions BEGIN SELECT RAISE(ABORT,'pull resolutions require explicit retention'); END;
CREATE UNIQUE INDEX pull_created_receipt_id ON command_evidence(account_id,json_extract(CAST(payload AS TEXT),'$.receipt.item.provider_id')) WHERE kind='github.pull_created' AND version=1;
-- Receipt-origin membership is cache evidence, separate from immutable authored resolution.
CREATE TABLE pull_creation_visibility(account_id TEXT NOT NULL,authorization_epoch TEXT NOT NULL CHECK(length(authorization_epoch) BETWEEN 1 AND 19),entity_id TEXT NOT NULL,command_id TEXT NOT NULL,PRIMARY KEY(account_id,entity_id),UNIQUE(account_id,command_id),FOREIGN KEY(account_id,entity_id) REFERENCES items(account_id,id) ON DELETE CASCADE,FOREIGN KEY(account_id,command_id) REFERENCES commands(account_id,command_id) ON DELETE RESTRICT) STRICT;
