-- Authored metadata is separate from evictable repository-option observations.
CREATE TABLE issue_draft_metadata(account_id TEXT NOT NULL,draft_id TEXT NOT NULL,metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json) AND octet_length(metadata_json)<=65536),PRIMARY KEY(account_id,draft_id),FOREIGN KEY(account_id,draft_id) REFERENCES issue_drafts(account_id,draft_id) ON DELETE RESTRICT) STRICT;
CREATE TRIGGER issue_draft_metadata_identity BEFORE UPDATE OF account_id,draft_id ON issue_draft_metadata BEGIN SELECT RAISE(ABORT,'immutable issue metadata draft identity'); END;
CREATE TRIGGER issue_draft_metadata_retained BEFORE DELETE ON issue_draft_metadata BEGIN SELECT RAISE(ABORT,'issue metadata drafts require explicit retention'); END;
DROP TRIGGER issue_submission_bound;
CREATE TRIGGER issue_submission_bound BEFORE INSERT ON issue_submissions WHEN NOT EXISTS(SELECT 1 FROM issue_drafts d JOIN commands c ON c.account_id=d.account_id WHERE d.account_id=NEW.account_id AND d.draft_id=NEW.draft_id AND d.generation=NEW.draft_generation AND c.command_id=NEW.command_id AND c.target_id=d.repository_id AND c.target_kind='repository' AND c.operation_kind='github.create_issue' AND (c.payload_version=2 OR(c.payload_version=1 AND NOT EXISTS(SELECT 1 FROM issue_draft_metadata m WHERE m.account_id=d.account_id AND m.draft_id=d.draft_id AND m.metadata_json<>'{"labels":[],"assignees":[],"milestone":null}'))) AND c.state='queued') BEGIN SELECT RAISE(ABORT,'invalid issue submission binding'); END;
DROP INDEX issue_created_receipt_id;
CREATE UNIQUE INDEX issue_created_receipt_id ON command_evidence(account_id,CASE version WHEN 1 THEN json_extract(CAST(payload AS TEXT),'$.receipt.item.provider_id') WHEN 2 THEN json_extract(CAST(payload AS TEXT),'$.core.provider_id') END) WHERE kind='github.issue_created' AND version IN(1,2);
CREATE TABLE repository_metadata_catalogs(account_id TEXT NOT NULL,repository_id TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN('labels','assignees','milestones')),authorization_epoch TEXT NOT NULL,authorization_view TEXT NOT NULL,binding_json TEXT NOT NULL CHECK(json_valid(binding_json) AND octet_length(binding_json)<=8192),generation INTEGER NOT NULL CHECK(generation>0),catalog_revision INTEGER NOT NULL CHECK(catalog_revision>0),cursor TEXT CHECK(cursor IS NULL OR octet_length(cursor)<=16384),pages INTEGER NOT NULL CHECK(pages BETWEEN 0 AND 20),complete INTEGER NOT NULL CHECK(complete IN(0,1)),truncated INTEGER NOT NULL CHECK(truncated IN(0,1)),evicted INTEGER NOT NULL DEFAULT 0 CHECK(evicted IN(0,1)),observed_at TEXT, sync_json TEXT NOT NULL CHECK(json_valid(sync_json)),PRIMARY KEY(account_id,repository_id,kind),FOREIGN KEY(account_id,repository_id) REFERENCES repositories(account_id,id) ON DELETE CASCADE) STRICT;
CREATE INDEX repository_metadata_catalogs_retention ON repository_metadata_catalogs(account_id,catalog_revision,repository_id,kind);
CREATE TABLE repository_metadata_options(account_id TEXT NOT NULL,repository_id TEXT NOT NULL,kind TEXT NOT NULL,provider_id TEXT NOT NULL CHECK(octet_length(provider_id) BETWEEN 1 AND 20),option_json TEXT NOT NULL CHECK(json_valid(option_json) AND octet_length(option_json)<=16384),search_key TEXT NOT NULL CHECK(octet_length(search_key)<=4096),seen_generation INTEGER NOT NULL CHECK(seen_generation>0),data_revision INTEGER NOT NULL CHECK(data_revision>0),observed_at TEXT NOT NULL,PRIMARY KEY(account_id,repository_id,kind,provider_id),FOREIGN KEY(account_id,repository_id,kind) REFERENCES repository_metadata_catalogs(account_id,repository_id,kind) ON DELETE CASCADE) STRICT;
CREATE INDEX repository_metadata_options_browse ON repository_metadata_options(account_id,repository_id,kind,search_key,provider_id);
CREATE INDEX repository_metadata_options_retention ON repository_metadata_options(account_id,data_revision,repository_id,kind,provider_id);
