/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppGitRouteRouteImport } from './routes/app/git/route'
import { Route as AuthOnboardingIndexRouteImport } from './routes/auth/onboarding/index'
import { Route as AppPullsIndexRouteImport } from './routes/app/pulls/index'
import { Route as AppIssuesIndexRouteImport } from './routes/app/issues/index'
import { Route as AppInboxIndexRouteImport } from './routes/app/inbox/index'
import { Route as AppGitIndexRouteImport } from './routes/app/git/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGitRouteRoute = AppGitRouteRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthOnboardingIndexRoute = AuthOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppPullsIndexRoute = AppPullsIndexRouteImport.update({
  id: '/pulls/',
  path: '/pulls/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIssuesIndexRoute = AppIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGitIndexRoute = AppGitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGitRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/git': typeof AppGitRouteRouteWithChildren
  '/app/git/': typeof AppGitIndexRoute
  '/app/inbox': typeof AppInboxIndexRoute
  '/app/issues': typeof AppIssuesIndexRoute
  '/app/pulls': typeof AppPullsIndexRoute
  '/auth/onboarding': typeof AuthOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/git': typeof AppGitIndexRoute
  '/app/inbox': typeof AppInboxIndexRoute
  '/app/issues': typeof AppIssuesIndexRoute
  '/app/pulls': typeof AppPullsIndexRoute
  '/auth/onboarding': typeof AuthOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/git': typeof AppGitRouteRouteWithChildren
  '/app/git/': typeof AppGitIndexRoute
  '/app/inbox/': typeof AppInboxIndexRoute
  '/app/issues/': typeof AppIssuesIndexRoute
  '/app/pulls/': typeof AppPullsIndexRoute
  '/auth/onboarding/': typeof AuthOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/git'
    | '/app/git/'
    | '/app/inbox'
    | '/app/issues'
    | '/app/pulls'
    | '/auth/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/git'
    | '/app/inbox'
    | '/app/issues'
    | '/app/pulls'
    | '/auth/onboarding'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/git'
    | '/app/git/'
    | '/app/inbox/'
    | '/app/issues/'
    | '/app/pulls/'
    | '/auth/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/git': {
      id: '/app/git'
      path: '/git'
      fullPath: '/app/git'
      preLoaderRoute: typeof AppGitRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/onboarding/': {
      id: '/auth/onboarding/'
      path: '/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/pulls/': {
      id: '/app/pulls/'
      path: '/pulls'
      fullPath: '/app/pulls'
      preLoaderRoute: typeof AppPullsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/issues/': {
      id: '/app/issues/'
      path: '/issues'
      fullPath: '/app/issues'
      preLoaderRoute: typeof AppIssuesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inbox/': {
      id: '/app/inbox/'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/git/': {
      id: '/app/git/'
      path: '/'
      fullPath: '/app/git/'
      preLoaderRoute: typeof AppGitIndexRouteImport
      parentRoute: typeof AppGitRouteRoute
    }
  }
}

interface AppGitRouteRouteChildren {
  AppGitIndexRoute: typeof AppGitIndexRoute
}

const AppGitRouteRouteChildren: AppGitRouteRouteChildren = {
  AppGitIndexRoute: AppGitIndexRoute,
}

const AppGitRouteRouteWithChildren = AppGitRouteRoute._addFileChildren(
  AppGitRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppGitRouteRoute: typeof AppGitRouteRouteWithChildren
  AppInboxIndexRoute: typeof AppInboxIndexRoute
  AppIssuesIndexRoute: typeof AppIssuesIndexRoute
  AppPullsIndexRoute: typeof AppPullsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppGitRouteRoute: AppGitRouteRouteWithChildren,
  AppInboxIndexRoute: AppInboxIndexRoute,
  AppIssuesIndexRoute: AppIssuesIndexRoute,
  AppPullsIndexRoute: AppPullsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthOnboardingIndexRoute: typeof AuthOnboardingIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthOnboardingIndexRoute: AuthOnboardingIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
