[package]
name = "git"
version = "0.1.0"
edition = "2024"

[dependencies]
tauri = { version = "2", features = [] }
tokio = { version = "1", features = ["process", "io-util", "time"] }
serde = "1.0.219"
base64 = "0.22"
logger = { path = "../logger" }
log = "0.4"

[lib]
name = "git"
path = "lib.rs"

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util", "macros"] }
tempfile = "3"
serial_test = "3"
