/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.2
 * Generated at: 2026-02-21T12:19:03.073065+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';
import { ZodError } from 'zod';
import * as types from './types';

export interface CommandHooks<T> {
  /** Called when Zod schema validation fails */
  onValidationError?: (error: ZodError) => void;

  /** Called when Tauri invoke fails (Rust error, serialization, etc.) */
  onInvokeError?: (error: unknown) => void;

  /** Called when command succeeds */
  onSuccess?: (result: T) => void;

  /** Called after command settles (success or error) */
  onSettled?: () => void;
}


export async function lastCommit(hooks?: CommandHooks<types.CommitInfo>): Promise<types.CommitInfo> {
  try {
    const data = await invoke<types.CommitInfo>('last_commit');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function commitById(params: types.CommitByIdParams, hooks?: CommandHooks<types.FullCommitInfo>): Promise<types.FullCommitInfo> {
  try {
    const result = types.CommitByIdParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.FullCommitInfo>('commit_by_id', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function createCommit(params: types.CreateCommitParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CreateCommitParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('create_commit', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function addLocalGitRepo(params: types.AddLocalGitRepoParams, hooks?: CommandHooks<types.RepoSitoryStore | null>): Promise<types.RepoSitoryStore | null> {
  try {
    const result = types.AddLocalGitRepoParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepoSitoryStore | null>('add_local_git_repo', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function selectRepository(params: types.SelectRepositoryParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.SelectRepositoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('select_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function openWithApp(params: types.OpenWithAppParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.OpenWithAppParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('open_with_app', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function getPatchByFilePath(params: types.GetPatchByFilePathParams, hooks?: CommandHooks<types.FileDiff>): Promise<types.FileDiff> {
  try {
    const result = types.GetPatchByFilePathParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.FileDiff>('get_patch_by_file_path', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function history(params: types.HistoryParams, hooks?: CommandHooks<types.CommitInfo[]>): Promise<types.CommitInfo[]> {
  try {
    const result = types.HistoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.CommitInfo[]>('history', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function historyGraph(params: types.HistoryGraphParams, hooks?: CommandHooks<types.HistoryGraphResponse>): Promise<types.HistoryGraphResponse> {
  try {
    const result = types.HistoryGraphParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.HistoryGraphResponse>('history_graph', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function listRepositories(params: types.ListRepositoriesParams, hooks?: CommandHooks<types.RepositoryInfo[]>): Promise<types.RepositoryInfo[]> {
  try {
    const result = types.ListRepositoriesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepositoryInfo[]>('list_repositories', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function addRepository(params: types.AddRepositoryParams, hooks?: CommandHooks<types.RepositoryInfo>): Promise<types.RepositoryInfo> {
  try {
    const result = types.AddRepositoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepositoryInfo>('add_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function removeRepository(params: types.RemoveRepositoryParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.RemoveRepositoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('remove_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function refreshRepositoryInfo(params: types.RefreshRepositoryInfoParams, hooks?: CommandHooks<types.RepositoryInfo>): Promise<types.RepositoryInfo> {
  try {
    const result = types.RefreshRepositoryInfoParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepositoryInfo>('refresh_repository_info', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function repositoryOrigin(hooks?: CommandHooks<types.RepositoryOrigin>): Promise<types.RepositoryOrigin> {
  try {
    const data = await invoke<types.RepositoryOrigin>('repository_origin');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function getDiff(params: types.GetDiffParams, hooks?: CommandHooks<types.FileDiff>): Promise<types.FileDiff> {
  try {
    const result = types.GetDiffParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.FileDiff>('get_diff', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function currentBranch(hooks?: CommandHooks<types.Branch>): Promise<types.Branch> {
  try {
    const data = await invoke<types.Branch>('current_branch');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function listBranches(params: types.ListBranchesParams, hooks?: CommandHooks<types.BranchInfo[]>): Promise<types.BranchInfo[]> {
  try {
    const result = types.ListBranchesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.BranchInfo[]>('list_branches', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function statusAheadBehind(hooks?: CommandHooks<types.AheadBehindStatus>): Promise<types.AheadBehindStatus> {
  try {
    const data = await invoke<types.AheadBehindStatus>('status_ahead_behind');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function getBranchInfo(params: types.GetBranchInfoParams, hooks?: CommandHooks<types.BranchInfo>): Promise<types.BranchInfo> {
  try {
    const result = types.GetBranchInfoParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.BranchInfo>('get_branch_info', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function switchBranch(params: types.SwitchBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.SwitchBranchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('switch_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function createBranch(params: types.CreateBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CreateBranchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('create_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function push(hooks?: CommandHooks<string>): Promise<string> {
  try {
    const data = await invoke<string>('push');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function publishBranch(hooks?: CommandHooks<string>): Promise<string> {
  try {
    const data = await invoke<string>('publish_branch');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function pull(hooks?: CommandHooks<string>): Promise<string> {
  try {
    const data = await invoke<string>('pull');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function hasUncommittedChanges(hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const data = await invoke<boolean>('has_uncommitted_changes');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function currentBranchStash(hooks?: CommandHooks<types.BranchStash | null>): Promise<types.BranchStash | null> {
  try {
    const data = await invoke<types.BranchStash | null>('current_branch_stash');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function popCurrentBranchStash(hooks?: CommandHooks<string>): Promise<string> {
  try {
    const data = await invoke<string>('pop_current_branch_stash');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function checkForUpdateByChannel(params: types.CheckForUpdateByChannelParams, hooks?: CommandHooks<types.UpdateCheckResponse>): Promise<types.UpdateCheckResponse> {
  try {
    const result = types.CheckForUpdateByChannelParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.UpdateCheckResponse>('check_for_update_by_channel', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function installUpdateByChannel(params: types.InstallUpdateByChannelParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.InstallUpdateByChannelParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('install_update_by_channel', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function gitVersion(hooks?: CommandHooks<string>): Promise<string> {
  try {
    const data = await invoke<string>('git_version');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function getStatus(hooks?: CommandHooks<types.GetStatusResponse>): Promise<types.GetStatusResponse> {
  try {
    const data = await invoke<types.GetStatusResponse>('get_status');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function gitFetch(hooks?: CommandHooks<string>): Promise<string> {
  try {
    const data = await invoke<string>('git_fetch');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function gitAdd(params: types.GitAddParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitAddParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('git_add', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function gitRemove(params: types.GitRemoveParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitRemoveParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('git_remove', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function gitDiscard(params: types.GitDiscardParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitDiscardParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('git_discard', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


