/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.2
 * Generated at: 2026-10-07T20:28:59.831582+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';
import { ZodError } from 'zod';
import * as types from './types';

export interface CommandHooks<T> {
  /** Called when Zod schema validation fails */
  onValidationError?: (error: ZodError) => void;

  /** Called when Tauri invoke fails (Rust error, serialization, etc.) */
  onInvokeError?: (error: unknown) => void;

  /** Called when command succeeds */
  onSuccess?: (result: T) => void;

  /** Called after command settles (success or error) */
  onSettled?: () => void;
}

export async function repositoryOrigin(params: types.RepositoryOriginParams, hooks?: CommandHooks<types.RepositoryOrigin>): Promise<types.RepositoryOrigin> {
  try {
    const result = types.RepositoryOriginParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepositoryOrigin>('repository_origin', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationAccounts(params: types.CollaborationAccountsParams, hooks?: CommandHooks<types.AccountSnapshot>): Promise<types.AccountSnapshot> {
  try {
    const result = types.CollaborationAccountsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.AccountSnapshot>('collaboration_accounts', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationConnectGithub(params: types.CollaborationConnectGithubParams, hooks?: CommandHooks<types.RemoteAccount>): Promise<types.RemoteAccount> {
  try {
    const result = types.CollaborationConnectGithubParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RemoteAccount>('collaboration_connect_github', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationConnectGitlab(params: types.CollaborationConnectGitlabParams, hooks?: CommandHooks<types.RemoteAccount>): Promise<types.RemoteAccount> {
  try {
    const result = types.CollaborationConnectGitlabParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RemoteAccount>('collaboration_connect_gitlab', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationConnectBitbucketCloud(params: types.CollaborationConnectBitbucketCloudParams, hooks?: CommandHooks<types.RemoteAccount>): Promise<types.RemoteAccount> {
  try {
    const result = types.CollaborationConnectBitbucketCloudParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RemoteAccount>('collaboration_connect_bitbucket_cloud', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationDiscoverGithubCli(params: types.CollaborationDiscoverGithubCliParams, hooks?: CommandHooks<types.GithubCliDiscovery>): Promise<types.GithubCliDiscovery> {
  try {
    const result = types.CollaborationDiscoverGithubCliParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.GithubCliDiscovery>('collaboration_discover_github_cli', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationConnectGithubCli(params: types.CollaborationConnectGithubCliParams, hooks?: CommandHooks<types.RemoteAccount>): Promise<types.RemoteAccount> {
  try {
    const result = types.CollaborationConnectGithubCliParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RemoteAccount>('collaboration_connect_github_cli', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationDisconnect(params: types.CollaborationDisconnectParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CollaborationDisconnectParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('collaboration_disconnect', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationRepositories(params: types.CollaborationRepositoriesParams, hooks?: CommandHooks<types.RepositorySnapshot>): Promise<types.RepositorySnapshot> {
  try {
    const result = types.CollaborationRepositoriesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepositorySnapshot>('collaboration_repositories', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationSelectRepository(params: types.CollaborationSelectRepositoryParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CollaborationSelectRepositoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('collaboration_select_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationItems(params: types.CollaborationItemsParams, hooks?: CommandHooks<types.ItemPage>): Promise<types.ItemPage> {
  try {
    const result = types.CollaborationItemsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ItemPage>('collaboration_items', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationItem(params: types.CollaborationItemParams, hooks?: CommandHooks<types.ItemSnapshot>): Promise<types.ItemSnapshot> {
  try {
    const result = types.CollaborationItemParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ItemSnapshot>('collaboration_item', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationInbox(params: types.CollaborationInboxParams, hooks?: CommandHooks<types.InboxPage>): Promise<types.InboxPage> {
  try {
    const result = types.CollaborationInboxParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.InboxPage>('collaboration_inbox', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationSetLocalInboxState(params: types.CollaborationSetLocalInboxStateParams, hooks?: CommandHooks<types.LocalInboxWriteReceipt>): Promise<types.LocalInboxWriteReceipt> {
  try {
    const result = types.CollaborationSetLocalInboxStateParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.LocalInboxWriteReceipt>('collaboration_set_local_inbox_state', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationRefresh(params: types.CollaborationRefreshParams, hooks?: CommandHooks<types.RefreshReceipt>): Promise<types.RefreshReceipt> {
  try {
    const result = types.CollaborationRefreshParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RefreshReceipt>('collaboration_refresh', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationChangesSince(params: types.CollaborationChangesSinceParams, hooks?: CommandHooks<types.ChangePage>): Promise<types.ChangePage> {
  try {
    const result = types.CollaborationChangesSinceParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ChangePage>('collaboration_changes_since', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationSaveDraft(params: types.CollaborationSaveDraftParams, hooks?: CommandHooks<types.LocalDraft>): Promise<types.LocalDraft> {
  try {
    const result = types.CollaborationSaveDraftParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.LocalDraft>('collaboration_save_draft', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationDraft(params: types.CollaborationDraftParams, hooks?: CommandHooks<types.LocalDraft | null>): Promise<types.LocalDraft | null> {
  try {
    const result = types.CollaborationDraftParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.LocalDraft | null>('collaboration_draft', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationContextualCapabilities(params: types.CollaborationContextualCapabilitiesParams, hooks?: CommandHooks<types.ContextualCapabilitySnapshot>): Promise<types.ContextualCapabilitySnapshot> {
  try {
    const result = types.CollaborationContextualCapabilitiesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ContextualCapabilitySnapshot>('collaboration_contextual_capabilities', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationCapabilities(params: types.CollaborationCapabilitiesParams, hooks?: CommandHooks<types.CapabilitySnapshot>): Promise<types.CapabilitySnapshot> {
  try {
    const result = types.CollaborationCapabilitiesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.CapabilitySnapshot>('collaboration_capabilities', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationResolveResource(params: types.CollaborationResolveResourceParams, hooks?: CommandHooks<types.ResourceResolution>): Promise<types.ResourceResolution> {
  try {
    const result = types.CollaborationResolveResourceParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ResourceResolution>('collaboration_resolve_resource', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationDrafts(params: types.CollaborationDraftsParams, hooks?: CommandHooks<types.DraftPage>): Promise<types.DraftPage> {
  try {
    const result = types.CollaborationDraftsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.DraftPage>('collaboration_drafts', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationExportDraft(params: types.CollaborationExportDraftParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.CollaborationExportDraftParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('collaboration_export_draft', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationDetail(params: types.CollaborationDetailParams, hooks?: CommandHooks<types.DetailSnapshot>): Promise<types.DetailSnapshot> {
  try {
    const result = types.CollaborationDetailParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.DetailSnapshot>('collaboration_detail', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationPullCommits(params: types.CollaborationPullCommitsParams, hooks?: CommandHooks<types.PullCommitSnapshot>): Promise<types.PullCommitSnapshot> {
  try {
    const result = types.CollaborationPullCommitsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PullCommitSnapshot>('collaboration_pull_commits', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationHydrateDetail(params: types.CollaborationHydrateDetailParams, hooks?: CommandHooks<types.RefreshReceipt>): Promise<types.RefreshReceipt> {
  try {
    const result = types.CollaborationHydrateDetailParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RefreshReceipt>('collaboration_hydrate_detail', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationOpenLocalPullCommit(params: types.CollaborationOpenLocalPullCommitParams, hooks?: CommandHooks<types.OpenLocalPullCommitReceipt>): Promise<types.OpenLocalPullCommitReceipt> {
  try {
    const result = types.CollaborationOpenLocalPullCommitParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.OpenLocalPullCommitReceipt>('collaboration_open_local_pull_commit', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function startPickaxe(params: types.StartPickaxeParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.StartPickaxeParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('start_pickaxe', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function cancelPickaxe(params: types.CancelPickaxeParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.CancelPickaxeParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('cancel_pickaxe', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function openExternalUrl(params: types.OpenExternalUrlParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.OpenExternalUrlParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('open_external_url', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function getRepoOperation(params: types.GetRepoOperationParams, hooks?: CommandHooks<types.RepoOperation>): Promise<types.RepoOperation> {
  try {
    const result = types.GetRepoOperationParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepoOperation>('get_repo_operation', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function rebasePlan(params: types.RebasePlanParams, hooks?: CommandHooks<types.RebasePlan>): Promise<types.RebasePlan> {
  try {
    const result = types.RebasePlanParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RebasePlan>('rebase_plan', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function rebaseStart(params: types.RebaseStartParams, hooks?: CommandHooks<types.RepoOperation>): Promise<types.RepoOperation> {
  try {
    const result = types.RebaseStartParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepoOperation>('rebase_start', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function rebaseContinue(params: types.RebaseContinueParams, hooks?: CommandHooks<types.RepoOperation>): Promise<types.RepoOperation> {
  try {
    const result = types.RebaseContinueParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepoOperation>('rebase_continue', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function rebaseSkip(params: types.RebaseSkipParams, hooks?: CommandHooks<types.RepoOperation>): Promise<types.RepoOperation> {
  try {
    const result = types.RebaseSkipParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepoOperation>('rebase_skip', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function rebaseAbort(params: types.RebaseAbortParams, hooks?: CommandHooks<types.RepoOperation>): Promise<types.RepoOperation> {
  try {
    const result = types.RebaseAbortParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepoOperation>('rebase_abort', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function rebaseAbortPreview(params: types.RebaseAbortPreviewParams, hooks?: CommandHooks<types.RebaseAbortPreview>): Promise<types.RebaseAbortPreview> {
  try {
    const result = types.RebaseAbortPreviewParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RebaseAbortPreview>('rebase_abort_preview', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function rebaseUpdateTodo(params: types.RebaseUpdateTodoParams, hooks?: CommandHooks<types.RepoOperation>): Promise<types.RepoOperation> {
  try {
    const result = types.RebaseUpdateTodoParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepoOperation>('rebase_update_todo', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function rebaseSetCommitMessage(params: types.RebaseSetCommitMessageParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.RebaseSetCommitMessageParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('rebase_set_commit_message', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function rebaseResolveConflict(params: types.RebaseResolveConflictParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.RebaseResolveConflictParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('rebase_resolve_conflict', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function getPatchByFilePath(params: types.GetPatchByFilePathParams, hooks?: CommandHooks<types.FileDiff>): Promise<types.FileDiff> {
  try {
    const result = types.GetPatchByFilePathParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.FileDiff>('get_patch_by_file_path', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function currentBranch(params: types.CurrentBranchParams, hooks?: CommandHooks<types.Branch>): Promise<types.Branch> {
  try {
    const result = types.CurrentBranchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Branch>('current_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function listBranches(params: types.ListBranchesParams, hooks?: CommandHooks<types.BranchInfo[]>): Promise<types.BranchInfo[]> {
  try {
    const result = types.ListBranchesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.BranchInfo[]>('list_branches', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function statusAheadBehind(params: types.StatusAheadBehindParams, hooks?: CommandHooks<types.AheadBehindStatus>): Promise<types.AheadBehindStatus> {
  try {
    const result = types.StatusAheadBehindParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.AheadBehindStatus>('status_ahead_behind', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function getBranchInfo(params: types.GetBranchInfoParams, hooks?: CommandHooks<types.BranchInfo>): Promise<types.BranchInfo> {
  try {
    const result = types.GetBranchInfoParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.BranchInfo>('get_branch_info', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function switchBranch(params: types.SwitchBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.SwitchBranchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('switch_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function createBranch(params: types.CreateBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CreateBranchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('create_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function renameBranch(params: types.RenameBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.RenameBranchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('rename_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function deleteLocalBranch(params: types.DeleteLocalBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.DeleteLocalBranchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('delete_local_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function deleteRemoteBranch(params: types.DeleteRemoteBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.DeleteRemoteBranchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('delete_remote_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function setBranchUpstream(params: types.SetBranchUpstreamParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.SetBranchUpstreamParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('set_branch_upstream', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function unsetBranchUpstream(params: types.UnsetBranchUpstreamParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.UnsetBranchUpstreamParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('unset_branch_upstream', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function push(params: types.PushParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.PushParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('push', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function publishBranch(params: types.PublishBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.PublishBranchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('publish_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function pull(params: types.PullParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.PullParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('pull', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function hasUncommittedChanges(params: types.HasUncommittedChangesParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.HasUncommittedChangesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('has_uncommitted_changes', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function currentBranchStash(params: types.CurrentBranchStashParams, hooks?: CommandHooks<types.BranchStash | null>): Promise<types.BranchStash | null> {
  try {
    const result = types.CurrentBranchStashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.BranchStash | null>('current_branch_stash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function popCurrentBranchStash(params: types.PopCurrentBranchStashParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.PopCurrentBranchStashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('pop_current_branch_stash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationDemandActivity(params: types.CollaborationDemandActivityParams, hooks?: CommandHooks<types.DemandOwnerActivity>): Promise<types.DemandOwnerActivity> {
  try {
    const result = types.CollaborationDemandActivityParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.DemandOwnerActivity>('collaboration_demand_activity', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationAcquireDemand(params: types.CollaborationAcquireDemandParams, hooks?: CommandHooks<types.DemandLeaseReceipt>): Promise<types.DemandLeaseReceipt> {
  try {
    const result = types.CollaborationAcquireDemandParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.DemandLeaseReceipt>('collaboration_acquire_demand', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationRenewDemand(params: types.CollaborationRenewDemandParams, hooks?: CommandHooks<types.DemandRenewalReceipt>): Promise<types.DemandRenewalReceipt> {
  try {
    const result = types.CollaborationRenewDemandParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.DemandRenewalReceipt>('collaboration_renew_demand', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationReleaseDemand(params: types.CollaborationReleaseDemandParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.CollaborationReleaseDemandParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('collaboration_release_demand', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationInspectDemandOwner(params: types.CollaborationInspectDemandOwnerParams, hooks?: CommandHooks<types.DemandOwnerActivity>): Promise<types.DemandOwnerActivity> {
  try {
    const result = types.CollaborationInspectDemandOwnerParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.DemandOwnerActivity>('collaboration_inspect_demand_owner', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationSetDemandOwnerActivity(params: types.CollaborationSetDemandOwnerActivityParams, hooks?: CommandHooks<types.DemandOwnerActivity>): Promise<types.DemandOwnerActivity> {
  try {
    const result = types.CollaborationSetDemandOwnerActivityParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.DemandOwnerActivity>('collaboration_set_demand_owner_activity', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationDisposeDemandOwner(params: types.CollaborationDisposeDemandOwnerParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.CollaborationDisposeDemandOwnerParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('collaboration_dispose_demand_owner', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function lastCommit(params: types.LastCommitParams, hooks?: CommandHooks<types.CommitInfo>): Promise<types.CommitInfo> {
  try {
    const result = types.LastCommitParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.CommitInfo>('last_commit', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function commitById(params: types.CommitByIdParams, hooks?: CommandHooks<types.FullCommitInfo>): Promise<types.FullCommitInfo> {
  try {
    const result = types.CommitByIdParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.FullCommitInfo>('commit_by_id', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function createCommit(params: types.CreateCommitParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CreateCommitParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('create_commit', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function commitAuthors(params: types.CommitAuthorsParams, hooks?: CommandHooks<types.Author[]>): Promise<types.Author[]> {
  try {
    const result = types.CommitAuthorsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.Author[]>('commit_authors', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationLocalLinks(params: types.CollaborationLocalLinksParams, hooks?: CommandHooks<types.LocalLinkInspection>): Promise<types.LocalLinkInspection> {
  try {
    const result = types.CollaborationLocalLinksParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.LocalLinkInspection>('collaboration_local_links', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationConfirmLocalLink(params: types.CollaborationConfirmLocalLinkParams, hooks?: CommandHooks<types.LocalLinkWriteReceipt>): Promise<types.LocalLinkWriteReceipt> {
  try {
    const result = types.CollaborationConfirmLocalLinkParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.LocalLinkWriteReceipt>('collaboration_confirm_local_link', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationRemoveLocalLink(params: types.CollaborationRemoveLocalLinkParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CollaborationRemoveLocalLinkParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('collaboration_remove_local_link', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationSaveTransportBinding(params: types.CollaborationSaveTransportBindingParams, hooks?: CommandHooks<types.LocalTransportBinding>): Promise<types.LocalTransportBinding> {
  try {
    const result = types.CollaborationSaveTransportBindingParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.LocalTransportBinding>('collaboration_save_transport_binding', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationRemoveTransportBinding(params: types.CollaborationRemoveTransportBindingParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CollaborationRemoveTransportBindingParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('collaboration_remove_transport_binding', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationLocalClones(params: types.CollaborationLocalClonesParams, hooks?: CommandHooks<types.LocalCloneSnapshot>): Promise<types.LocalCloneSnapshot> {
  try {
    const result = types.CollaborationLocalClonesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.LocalCloneSnapshot>('collaboration_local_clones', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationValidateLocalNavigation(params: types.CollaborationValidateLocalNavigationParams, hooks?: CommandHooks<types.LocalNavigationReceipt>): Promise<types.LocalNavigationReceipt> {
  try {
    const result = types.CollaborationValidateLocalNavigationParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.LocalNavigationReceipt>('collaboration_validate_local_navigation', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function listRepositories(params: types.ListRepositoriesParams, hooks?: CommandHooks<types.RepositoryInfo[]>): Promise<types.RepositoryInfo[]> {
  try {
    const result = types.ListRepositoriesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepositoryInfo[]>('list_repositories', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function addRepository(params: types.AddRepositoryParams, hooks?: CommandHooks<types.RepositoryInfo>): Promise<types.RepositoryInfo> {
  try {
    const result = types.AddRepositoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepositoryInfo>('add_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function removeRepository(params: types.RemoveRepositoryParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.RemoveRepositoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('remove_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function refreshRepositoryInfo(params: types.RefreshRepositoryInfoParams, hooks?: CommandHooks<types.RepositoryInfo>): Promise<types.RepositoryInfo> {
  try {
    const result = types.RefreshRepositoryInfoParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepositoryInfo>('refresh_repository_info', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function gitVersion(params: types.GitVersionParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitVersionParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('git_version', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function getStatus(params: types.GetStatusParams, hooks?: CommandHooks<types.GetStatusResponse>): Promise<types.GetStatusResponse> {
  try {
    const result = types.GetStatusParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.GetStatusResponse>('get_status', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function gitFetch(params: types.GitFetchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitFetchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('git_fetch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function gitAdd(params: types.GitAddParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitAddParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('git_add', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function gitRemove(params: types.GitRemoveParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitRemoveParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('git_remove', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function gitDiscard(params: types.GitDiscardParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitDiscardParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('git_discard', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function gitApplyPatchBlock(params: types.GitApplyPatchBlockParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitApplyPatchBlockParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('git_apply_patch_block', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function readWorktreeFile(params: types.ReadWorktreeFileParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.ReadWorktreeFileParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('read_worktree_file', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function writeWorktreeFile(params: types.WriteWorktreeFileParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.WriteWorktreeFileParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('write_worktree_file', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationPlanPullCheckout(params: types.CollaborationPlanPullCheckoutParams, hooks?: CommandHooks<types.PullCheckoutPlan>): Promise<types.PullCheckoutPlan> {
  try {
    const result = types.CollaborationPlanPullCheckoutParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PullCheckoutPlan>('collaboration_plan_pull_checkout', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationExecutePullCheckout(params: types.CollaborationExecutePullCheckoutParams, hooks?: CommandHooks<types.CollaborationPullCheckoutReceipt>): Promise<types.CollaborationPullCheckoutReceipt> {
  try {
    const result = types.CollaborationExecutePullCheckoutParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.CollaborationPullCheckoutReceipt>('collaboration_execute_pull_checkout', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function history(params: types.HistoryParams, hooks?: CommandHooks<types.CommitInfo[]>): Promise<types.CommitInfo[]> {
  try {
    const result = types.HistoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.CommitInfo[]>('history', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function historyGraph(params: types.HistoryGraphParams, hooks?: CommandHooks<types.HistoryGraphResponse>): Promise<types.HistoryGraphResponse> {
  try {
    const result = types.HistoryGraphParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.HistoryGraphResponse>('history_graph', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function commitActivity(params: types.CommitActivityParams, hooks?: CommandHooks<types.CommitActivityResponse>): Promise<types.CommitActivityResponse> {
  try {
    const result = types.CommitActivityParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.CommitActivityResponse>('commit_activity', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function stashList(params: types.StashListParams, hooks?: CommandHooks<types.StashEntry[]>): Promise<types.StashEntry[]> {
  try {
    const result = types.StashListParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.StashEntry[]>('stash_list', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function stashQuickStat(params: types.StashQuickStatParams, hooks?: CommandHooks<types.StashQuickStat>): Promise<types.StashQuickStat> {
  try {
    const result = types.StashQuickStatParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.StashQuickStat>('stash_quick_stat', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function stashShow(params: types.StashShowParams, hooks?: CommandHooks<types.StashShowResponse>): Promise<types.StashShowResponse> {
  try {
    const result = types.StashShowParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.StashShowResponse>('stash_show', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function stashPush(params: types.StashPushParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.StashPushParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('stash_push', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function stashPop(params: types.StashPopParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.StashPopParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('stash_pop', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function stashApply(params: types.StashApplyParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.StashApplyParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('stash_apply', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function stashDrop(params: types.StashDropParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.StashDropParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('stash_drop', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function stashClear(params: types.StashClearParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.StashClearParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('stash_clear', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function stashBranch(params: types.StashBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.StashBranchParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('stash_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function stashRestoreFile(params: types.StashRestoreFileParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.StashRestoreFileParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('stash_restore_file', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationHarnessControl(params: types.CollaborationHarnessControlParams, hooks?: CommandHooks<types.HarnessReceipt>): Promise<types.HarnessReceipt> {
  try {
    const result = types.CollaborationHarnessControlParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.HarnessReceipt>('collaboration_harness_control', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationHarnessStatus(params: types.CollaborationHarnessStatusParams, hooks?: CommandHooks<types.HarnessStatus>): Promise<types.HarnessStatus> {
  try {
    const result = types.CollaborationHarnessStatusParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.HarnessStatus>('collaboration_harness_status', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationHarnessViewManifest(params: types.CollaborationHarnessViewManifestParams, hooks?: CommandHooks<types.HarnessViewManifest>): Promise<types.HarnessViewManifest> {
  try {
    const result = types.CollaborationHarnessViewManifestParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.HarnessViewManifest>('collaboration_harness_view_manifest', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationPullFiles(params: types.CollaborationPullFilesParams, hooks?: CommandHooks<types.PullFileSnapshot>): Promise<types.PullFileSnapshot> {
  try {
    const result = types.CollaborationPullFilesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PullFileSnapshot>('collaboration_pull_files', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationPullFileArtifact(params: types.CollaborationPullFileArtifactParams, hooks?: CommandHooks<types.PullFileArtifactSnapshot>): Promise<types.PullFileArtifactSnapshot> {
  try {
    const result = types.CollaborationPullFileArtifactParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PullFileArtifactSnapshot>('collaboration_pull_file_artifact', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationHydratePullFile(params: types.CollaborationHydratePullFileParams, hooks?: CommandHooks<types.RefreshReceipt>): Promise<types.RefreshReceipt> {
  try {
    const result = types.CollaborationHydratePullFileParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RefreshReceipt>('collaboration_hydrate_pull_file', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationLoadLocalPullFile(params: types.CollaborationLoadLocalPullFileParams, hooks?: CommandHooks<types.PullFileArtifactSnapshot>): Promise<types.PullFileArtifactSnapshot> {
  try {
    const result = types.CollaborationLoadLocalPullFileParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PullFileArtifactSnapshot>('collaboration_load_local_pull_file', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function addLocalGitRepo(params: types.AddLocalGitRepoParams, hooks?: CommandHooks<types.RepoSitoryStore | null>): Promise<types.RepoSitoryStore | null> {
  try {
    const result = types.AddLocalGitRepoParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepoSitoryStore | null>('add_local_git_repo', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function cloneRepository(params: types.CloneRepositoryParams, hooks?: CommandHooks<types.RepositoryInfo>): Promise<types.RepositoryInfo> {
  try {
    const result = types.CloneRepositoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepositoryInfo>('clone_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function initRepository(params: types.InitRepositoryParams, hooks?: CommandHooks<types.RepositoryInfo>): Promise<types.RepositoryInfo> {
  try {
    const result = types.InitRepositoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RepositoryInfo>('init_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function cancelCloneRepository(params: types.CancelCloneRepositoryParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.CancelCloneRepositoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('cancel_clone_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function createRepoContext(params: types.CreateRepoContextParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CreateRepoContextParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('create_repo_context', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function disposeRepoContext(params: types.DisposeRepoContextParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.DisposeRepoContextParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('dispose_repo_context', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function disposeRepoContextOwner(params: types.DisposeRepoContextOwnerParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.DisposeRepoContextOwnerParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('dispose_repo_context_owner', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function invalidateRepoContextCaches(hooks?: CommandHooks<number>): Promise<number> {
  try {
    const data = await invoke<number>('invalidate_repo_context_caches');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function openWithApp(params: types.OpenWithAppParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.OpenWithAppParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('open_with_app', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function sessionPushToHistory(params: types.SessionPushToHistoryParams, hooks?: CommandHooks<types.SessionNavigationInfo>): Promise<types.SessionNavigationInfo> {
  try {
    const result = types.SessionPushToHistoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.SessionNavigationInfo>('session_push_to_history', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function sessionGoBack(params: types.SessionGoBackParams, hooks?: CommandHooks<types.SessionNavigationInfo | null>): Promise<types.SessionNavigationInfo | null> {
  try {
    const result = types.SessionGoBackParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.SessionNavigationInfo | null>('session_go_back', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function sessionGoForward(params: types.SessionGoForwardParams, hooks?: CommandHooks<types.SessionNavigationInfo | null>): Promise<types.SessionNavigationInfo | null> {
  try {
    const result = types.SessionGoForwardParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.SessionNavigationInfo | null>('session_go_forward', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function sessionGetNavigationState(params: types.SessionGetNavigationStateParams, hooks?: CommandHooks<types.SessionNavigationInfo>): Promise<types.SessionNavigationInfo> {
  try {
    const result = types.SessionGetNavigationStateParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.SessionNavigationInfo>('session_get_navigation_state', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function sessionClearHistory(params: types.SessionClearHistoryParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.SessionClearHistoryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('session_clear_history', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function checkForUpdateByChannel(params: types.CheckForUpdateByChannelParams, hooks?: CommandHooks<types.UpdateCheckResponse>): Promise<types.UpdateCheckResponse> {
  try {
    const result = types.CheckForUpdateByChannelParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.UpdateCheckResponse>('check_for_update_by_channel', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function downloadAndInstallUpdateByChannel(params: types.DownloadAndInstallUpdateByChannelParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.DownloadAndInstallUpdateByChannelParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<string>('download_and_install_update_by_channel', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationNotificationSubject(params: types.CollaborationNotificationSubjectParams, hooks?: CommandHooks<types.NotificationSubjectSnapshot>): Promise<types.NotificationSubjectSnapshot> {
  try {
    const result = types.CollaborationNotificationSubjectParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.NotificationSubjectSnapshot>('collaboration_notification_subject', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function collaborationDiscoverNotificationSubject(params: types.CollaborationDiscoverNotificationSubjectParams, hooks?: CommandHooks<types.RefreshReceipt>): Promise<types.RefreshReceipt> {
  try {
    const result = types.CollaborationDiscoverNotificationSubjectParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.RefreshReceipt>('collaboration_discover_notification_subject', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


