/**
 * Auto-generated command bindings for Tauri commands
 * Generated by tauri-typegen v0.3.2
 * Generated at: 2026-02-11T10:41:07Z
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';

import { ZodError } from 'zod';
import * as types from './types';

export interface CommandHooks<T> {
  /** Called when Zod schema validation fails */
  onValidationError?: (error: ZodError) => void;

  /** Called when Tauri invoke fails (Rust error, serialization, etc.) */
  onInvokeError?: (error: unknown) => void;

  /** Called when command succeeds */
  onSuccess?: (result: T) => void;

  /** Called after command settles (success or error) */
  onSettled?: () => void;
}

export async function history(params: types.HistoryParams, hooks?: CommandHooks<types.CommitInfo[]>): Promise<types.CommitInfo[]> {
  try {
    const result = types.HistoryParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.CommitInfo[]>('history', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function historyGraph(params: types.HistoryGraphParams, hooks?: CommandHooks<types.HistoryResponse>): Promise<types.HistoryResponse> {
  try {
    const result = types.HistoryGraphParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.HistoryResponse>('history_graph', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function searchCommits(params: types.SearchCommitsParams, hooks?: CommandHooks<types.SearchResult[]>): Promise<types.SearchResult[]> {
  try {
    const result = types.SearchCommitsParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.SearchResult[]>('search_commits', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function addLocalGitRepo(params: types.AddLocalGitRepoParams, hooks?: CommandHooks<types.RepoSitoryStore | null>): Promise<types.RepoSitoryStore | null> {
  try {
    const result = types.AddLocalGitRepoParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.RepoSitoryStore | null>('add_local_git_repo', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getDiff(params: types.GetDiffParams, hooks?: CommandHooks<types.FileDiff>): Promise<types.FileDiff> {
  try {
    const result = types.GetDiffParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.FileDiff>('get_diff', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getStatus(params: types.GetStatusParams, hooks?: CommandHooks<types.GetStatusResponse>): Promise<types.GetStatusResponse> {
  try {
    const result = types.GetStatusParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.GetStatusResponse>('get_status', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getFileStatus(params: types.GetFileStatusParams, hooks?: CommandHooks<types.FileStatus | null>): Promise<types.FileStatus | null> {
  try {
    const result = types.GetFileStatusParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.FileStatus | null>('get_file_status', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitAdd(params: types.GitAddParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitAddParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('git_add', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitRemove(params: types.GitRemoveParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitRemoveParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('git_remove', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitDiscard(params: types.GitDiscardParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitDiscardParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('git_discard', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitFetch(params: types.GitFetchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitFetchParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('git_fetch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitPush(params: types.GitPushParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitPushParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('git_push', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitPublishBranch(params: types.GitPublishBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitPublishBranchParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('git_publish_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitPull(params: types.GitPullParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitPullParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('git_pull', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitSwitchBranch(params: types.GitSwitchBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitSwitchBranchParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('git_switch_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitCreateBranch(params: types.GitCreateBranchParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.GitCreateBranchParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('git_create_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function hasUncommittedChanges(params: types.HasUncommittedChangesParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.HasUncommittedChangesParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<boolean>('has_uncommitted_changes', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function gitVersion(hooks?: CommandHooks<string>): Promise<string> {
  try {
    const data = await invoke<string>('git_version');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function getPatchByFilePath(params: types.GetPatchByFilePathParams, hooks?: CommandHooks<types.FileDiff>): Promise<types.FileDiff> {
  try {
    const result = types.GetPatchByFilePathParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.FileDiff>('get_patch_by_file_path', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function repositoryOrigin(params: types.RepositoryOriginParams, hooks?: CommandHooks<types.RepositoryOrigin>): Promise<types.RepositoryOrigin> {
  try {
    const result = types.RepositoryOriginParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.RepositoryOrigin>('repository_origin', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function listRepositories(params: types.ListRepositoriesParams, hooks?: CommandHooks<types.RepositoryInfo[]>): Promise<types.RepositoryInfo[]> {
  try {
    const result = types.ListRepositoriesParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.RepositoryInfo[]>('list_repositories', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function addRepository(params: types.AddRepositoryParams, hooks?: CommandHooks<types.RepositoryInfo>): Promise<types.RepositoryInfo> {
  try {
    const result = types.AddRepositoryParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.RepositoryInfo>('add_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function removeRepository(params: types.RemoveRepositoryParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.RemoveRepositoryParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<void>('remove_repository', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function refreshRepositoryInfo(params: types.RefreshRepositoryInfoParams, hooks?: CommandHooks<types.RepositoryInfo>): Promise<types.RepositoryInfo> {
  try {
    const result = types.RefreshRepositoryInfoParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.RepositoryInfo>('refresh_repository_info', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function lastCommit(params: types.LastCommitParams, hooks?: CommandHooks<types.CommitInfo>): Promise<types.CommitInfo> {
  try {
    const result = types.LastCommitParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.CommitInfo>('last_commit', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function commitById(params: types.CommitByIdParams, hooks?: CommandHooks<types.FullCommitInfo>): Promise<types.FullCommitInfo> {
  try {
    const result = types.CommitByIdParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.FullCommitInfo>('commit_by_id', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function createCommit(params: types.CreateCommitParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CreateCommitParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('create_commit', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function createEmptyCommit(params: types.CreateEmptyCommitParams, hooks?: CommandHooks<string>): Promise<string> {
  try {
    const result = types.CreateEmptyCommitParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<string>('create_empty_commit', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function currentBranch(params: types.CurrentBranchParams, hooks?: CommandHooks<types.Branch>): Promise<types.Branch> {
  try {
    const result = types.CurrentBranchParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.Branch>('current_branch', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function listBranches(params: types.ListBranchesParams, hooks?: CommandHooks<types.BranchInfo[]>): Promise<types.BranchInfo[]> {
  try {
    const result = types.ListBranchesParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.BranchInfo[]>('list_branches', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

export async function statusAheadBehind(params: types.StatusAheadBehindParams, hooks?: CommandHooks<types.AheadBehindStatus>): Promise<types.AheadBehindStatus> {
  try {
    const result = types.StatusAheadBehindParamsSchema.safeParse(params);
    
    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    
    const data = await invoke<types.AheadBehindStatus>('status_ahead_behind', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}

