/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.2
 * Generated at: 2026-10-03T13:47:51.097207+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

/**
 * Event Listeners
 * Type-safe event listener helpers for Tauri events
 */
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import * as types from './types';

/**
 * Listen for 'gitru:collaboration-change' events
 * @param handler - Callback function to handle the event
 * @returns Promise that resolves to an unlisten function
 */
export async function onGitruCollaborationChange(
  handler: (payload: types.ChangeHint) => void
): Promise<UnlistenFn> {
  return listen<types.ChangeHint>('gitru:collaboration-change', (event) => {
    handler(event.payload);
  });
}
