/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.2
 * Generated at: 2026-03-22T08:57:03.298542+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';


export const SwimlaneSchema = z.object({
  id: z.string(),
  color: z.coerce.number(),
  is_stash: z.coerce.boolean(),
});

export type Swimlane = z.infer<typeof SwimlaneSchema>;

export const BranchKindSchema = z.enum(["Local", "Remote"]);

export const AuthorSchema = z.object({
  name: z.string(),
  email: z.string(),
});

export type Author = z.infer<typeof AuthorSchema>;

export const CommitAuthorsSchema = z.object({
  author: AuthorSchema,
  committer: AuthorSchema,
  co_authors: z.array(AuthorSchema),
});

export type CommitAuthors = z.infer<typeof CommitAuthorsSchema>;

export const StashEntrySchema = z.object({
  index: z.coerce.number(),
  reference: z.string(),
  message: z.string(),
  branch: z.string().optional(),
  is_gitru: z.coerce.boolean(),
});

export type StashEntry = z.infer<typeof StashEntrySchema>;

export const UpdateCheckResponseSchema = z.object({
  available: z.coerce.boolean(),
  channel: z.string(),
  current_version: z.string(),
  version: z.string().optional(),
  notes: z.string().optional(),
  pub_date: z.string().optional(),
});

export type UpdateCheckResponse = z.infer<typeof UpdateCheckResponseSchema>;

export const GraphRefKindSchema = z.enum(["Local", "Remote", "Tag", "Stash", "Other"]);

export const GraphRefSchema = z.object({
  name: z.string(),
  kind: GraphRefKindSchema,
  is_head: z.coerce.boolean(),
});

export type GraphRef = z.infer<typeof GraphRefSchema>;

export const ParentEdgeSchema = z.object({
  oid: z.string(),
  lane: z.coerce.number(),
});

export type ParentEdge = z.infer<typeof ParentEdgeSchema>;

export const GraphRowTypeSchema = z.enum(["Commit", "Stash"]);

export const FileStatusKindSchema = z.enum(["IndexNew", "IndexModified", "IndexDeleted", "IndexRenamed", "IndexTypechange", "WorktreeNew", "WorktreeModified", "WorktreeDeleted", "WorktreeRenamed", "WorktreeTypechange", "WorktreeUnreadable", "Conflicted"]);

export const FileStatusSchema = z.object({
  path: z.string(),
  new_path: z.string().optional(),
  status: z.array(FileStatusKindSchema),
});

export type FileStatus = z.infer<typeof FileStatusSchema>;

export const CommitStatsSchema = z.object({
  insertions: z.coerce.number(),
  deletions: z.coerce.number(),
  files_changed: z.coerce.number(),
});

export type CommitStats = z.infer<typeof CommitStatsSchema>;

export const FullCommitInfoSchema = z.object({
  id: z.string(),
  timestamp: z.coerce.number(),
  summary: z.string(),
  body: z.string(),
  authors: CommitAuthorsSchema,
  stats: CommitStatsSchema,
  files: z.array(FileStatusSchema),
});

export type FullCommitInfo = z.infer<typeof FullCommitInfoSchema>;

export const GraphRowSchema = z.object({
  oid: z.string(),
  lane: z.coerce.number(),
  commit: FullCommitInfoSchema,
  parents: z.array(ParentEdgeSchema),
  type: GraphRowTypeSchema,
  refs: z.array(GraphRefSchema),
  heads: z.array(GraphRefSchema),
  remotes: z.array(GraphRefSchema),
  tags: z.array(GraphRefSchema),
  stashes: z.array(GraphRefSchema),
  input_swimlanes: z.array(SwimlaneSchema),
  output_swimlanes: z.array(SwimlaneSchema),
});

export type GraphRow = z.infer<typeof GraphRowSchema>;

export const AheadBehindStatusSchema = z.object({
  ahead: z.coerce.number(),
  behind: z.coerce.number(),
  local_branch: z.string(),
  local_branch_id: z.string(),
  upstream_branch: z.string().optional(),
  upstream_branch_id: z.string().optional(),
  is_published: z.coerce.boolean(),
});

export type AheadBehindStatus = z.infer<typeof AheadBehindStatusSchema>;

export const AssetDiffKindSchema = z.enum(["Image", "Binary"]);

export const AssetDiffEntrySchema = z.object({
  absolute_path: z.string(),
  mime: z.string(),
  bytes: z.coerce.number(),
  logical_path: z.string(),
  contents_base64: z.string(),
});

export type AssetDiffEntry = z.infer<typeof AssetDiffEntrySchema>;

export const AssetDiffSchema = z.object({
  kind: AssetDiffKindSchema,
  before: AssetDiffEntrySchema.optional(),
  after: AssetDiffEntrySchema.optional(),
});

export type AssetDiff = z.infer<typeof AssetDiffSchema>;

export const StashQuickStatSchema = z.object({
  reference: z.string(),
  files_changed: z.coerce.number(),
  insertions: z.coerce.number(),
  deletions: z.coerce.number(),
});

export type StashQuickStat = z.infer<typeof StashQuickStatSchema>;

export const RepositoryInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  origin: z.string().optional(),
  current_branch: z.string().optional(),
  ahead_behind: z.tuple([z.coerce.number(), z.coerce.number()]).optional(),
  has_uncommitted_changes: z.coerce.boolean(),
  last_updated: z.coerce.number(),
});

export type RepositoryInfo = z.infer<typeof RepositoryInfoSchema>;

export const GetStatusResponseSchema = z.object({
  files: z.array(FileStatusSchema),
});

export type GetStatusResponse = z.infer<typeof GetStatusResponseSchema>;

export const CommitInfoSchema = z.object({
  id: z.string(),
  summary: z.string(),
  body: z.string(),
  timestamp: z.coerce.number(),
  authors: CommitAuthorsSchema,
});

export type CommitInfo = z.infer<typeof CommitInfoSchema>;

export const BranchInfoSchema = z.object({
  name: z.string(),
  display_name: z.string(),
  is_remote: z.coerce.boolean(),
  is_head: z.coerce.boolean(),
  commit: CommitInfoSchema,
  upstream: z.string().optional(),
  ahead: z.coerce.number().optional(),
  behind: z.coerce.number().optional(),
});

export type BranchInfo = z.infer<typeof BranchInfoSchema>;

export const BranchSchema = z.object({
  name: z.string(),
  display_name: z.string(),
  is_remote: z.coerce.boolean(),
});

export type Branch = z.infer<typeof BranchSchema>;

export const RepositoryOriginSchema = z.object({
  remote_name: z.string(),
  remote_url: z.string(),
  host: z.string().optional(),
  provider: z.string().optional(),
  owner: z.string().optional(),
  repo: z.string().optional(),
  protocol: z.string(),
});

export type RepositoryOrigin = z.infer<typeof RepositoryOriginSchema>;

export const CommitMessageSchema = z.object({
  title: z.string(),
  description: z.string().optional(),
  co_authors: z.array(z.tuple([z.string(), z.string()])),
});

export type CommitMessage = z.infer<typeof CommitMessageSchema>;

export const PatchActionSchema = z.enum(["Stage", "Unstage", "Discard"]);

export const StashShowResponseSchema = z.object({
  reference: z.string(),
  stat: StashQuickStatSchema,
  files: z.array(FileStatusSchema),
});

export type StashShowResponse = z.infer<typeof StashShowResponseSchema>;

export const HistoryQuerySchema = z.object({
  cursor: z.string().optional(),
  limit: z.coerce.number(),
  search: z.string().optional(),
  branch: z.string().optional(),
  graph_state: z.string().optional(),
  include_local: z.coerce.boolean(),
  include_remotes: z.coerce.boolean(),
  include_tags: z.coerce.boolean(),
  include_stash: z.coerce.boolean(),
});

export type HistoryQuery = z.infer<typeof HistoryQuerySchema>;

export const DiffScopeSchema = z.enum(["Worktree", "Staged", "Unstaged"]);

export const DiffTextFileSchema = z.object({
  name: z.string(),
  contents: z.string(),
  byte_length: z.coerce.number(),
  encoding: z.string(),
});

export type DiffTextFile = z.infer<typeof DiffTextFileSchema>;

export const FileDiffSchema = z.object({
  patch: z.string(),
  asset_diff: AssetDiffSchema.optional(),
  oldFile: DiffTextFileSchema.optional(),
  newFile: DiffTextFileSchema.optional(),
});

export type FileDiff = z.infer<typeof FileDiffSchema>;

export const BranchStashSchema = z.object({
  reference: z.string(),
  message: z.string(),
  from_branch: z.string(),
  to_branch: z.string(),
  files_changed: z.coerce.number(),
  insertions: z.coerce.number(),
  deletions: z.coerce.number(),
});

export type BranchStash = z.infer<typeof BranchStashSchema>;

export const RepoSitoryStoreSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  origin: z.string().optional(),
  current_branch: z.string().optional(),
  ahead_behind: z.tuple([z.coerce.number(), z.coerce.number()]).optional(),
  has_uncommitted_changes: z.coerce.boolean(),
  last_updated: z.coerce.number(),
});

export type RepoSitoryStore = z.infer<typeof RepoSitoryStoreSchema>;

export const GraphPagingSchema = z.object({
  starting_cursor: z.string().optional(),
  has_more: z.coerce.boolean(),
});

export type GraphPaging = z.infer<typeof GraphPagingSchema>;

export const HistoryGraphResponseSchema = z.object({
  rows: z.array(GraphRowSchema),
  cursor: z.string().optional(),
  graph_state: z.string().optional(),
  has_more: z.coerce.boolean(),
  paging: GraphPagingSchema,
});

export type HistoryGraphResponse = z.infer<typeof HistoryGraphResponseSchema>;

export const PatchRangeSchema = z.object({
  start: z.coerce.number().optional(),
  count: z.coerce.number(),
});

export type PatchRange = z.infer<typeof PatchRangeSchema>;

export const UncommittedChangesStrategySchema = z.enum(["StashOnCurrentBranch", "BringChanges"]);


export const HistoryParamsSchema = z.object({
  skip: z.coerce.number(),limit: z.coerce.number(),
});

export const HistoryGraphParamsSchema = z.object({
  query: HistoryQuerySchema,
});

export const StashQuickStatParamsSchema = z.object({
  reference: z.string(),
});

export const StashShowParamsSchema = z.object({
  reference: z.string(),
});

export const StashPushParamsSchema = z.object({
  message: z.string().optional().optional(),includeUntracked: z.coerce.boolean().optional().optional(),
});

export const StashPopParamsSchema = z.object({
  reference: z.string().optional().optional(),
});

export const StashApplyParamsSchema = z.object({
  reference: z.string().optional().optional(),
});

export const StashDropParamsSchema = z.object({
  reference: z.string(),
});

export const StashBranchParamsSchema = z.object({
  branchName: z.string(),reference: z.string().optional().optional(),
});

export const StashRestoreFileParamsSchema = z.object({
  reference: z.string(),filePath: z.string(),
});

export const GetPatchByFilePathParamsSchema = z.object({
  filePath: z.string(),fileNewPath: z.string().optional().optional(),status: z.array(FileStatusKindSchema).optional().optional(),stashReference: z.string().optional().optional(),commitHash: z.string().optional().optional(),parentIndex: z.coerce.number().optional().optional(),diffScope: DiffScopeSchema.optional().optional(),
});

export const CheckForUpdateByChannelParamsSchema = z.object({
  channel: z.string(),
});

export const DownloadAndInstallUpdateByChannelParamsSchema = z.object({
  channel: z.string(),
});

export const GitAddParamsSchema = z.object({
  file: z.string().optional().optional(),files: z.array(z.string()).optional().optional(),
});

export const GitRemoveParamsSchema = z.object({
  file: z.string().optional().optional(),files: z.array(z.string()).optional().optional(),
});

export const GitDiscardParamsSchema = z.object({
  file: z.string().optional().optional(),files: z.array(z.string()).optional().optional(),all: z.coerce.boolean().optional().optional(),
});

export const GitApplyPatchBlockParamsSchema = z.object({
  filePath: z.string(),fileNewPath: z.string().optional().optional(),diffScope: DiffScopeSchema,additions: PatchRangeSchema,deletions: PatchRangeSchema,action: PatchActionSchema,
});

export const AddLocalGitRepoParamsSchema = z.object({
  repoPath: z.string(),
});

export const CloneRepositoryParamsSchema = z.object({
  url: z.string(),destinationPath: z.string(),operationId: z.string(),
});

export const InitRepositoryParamsSchema = z.object({
  repoPath: z.string(),
});

export const CancelCloneRepositoryParamsSchema = z.object({
  operationId: z.string(),
});

export const SelectRepositoryParamsSchema = z.object({
  repoId: z.string(),
});

export const OpenWithAppParamsSchema = z.object({
  filePath: z.string(),line: z.coerce.number().optional().optional(),app: z.string().optional().optional(),
});

export const ListRepositoriesParamsSchema = z.object({
  refreshStale: z.coerce.boolean().optional().optional(),
});

export const AddRepositoryParamsSchema = z.object({
  repo: RepositoryInfoSchema,
});

export const RemoveRepositoryParamsSchema = z.object({
  repoId: z.string(),
});

export const RefreshRepositoryInfoParamsSchema = z.object({
  repoId: z.string(),
});

export const ListBranchesParamsSchema = z.object({
  kind: BranchKindSchema,
});

export const GetBranchInfoParamsSchema = z.object({
  branchName: z.string(),
});

export const SwitchBranchParamsSchema = z.object({
  branch: z.string(),strategy: UncommittedChangesStrategySchema.optional().optional(),
});

export const CreateBranchParamsSchema = z.object({
  branch: z.string(),strategy: UncommittedChangesStrategySchema.optional().optional(),
});

export const CommitByIdParamsSchema = z.object({
  hash: z.string(),
});

export const CreateCommitParamsSchema = z.object({
  commitMeta: CommitMessageSchema,allowEmpty: z.coerce.boolean(),
});




export type HistoryParams = z.infer<typeof HistoryParamsSchema>;

export type HistoryGraphParams = z.infer<typeof HistoryGraphParamsSchema>;

export type StashQuickStatParams = z.infer<typeof StashQuickStatParamsSchema>;

export type StashShowParams = z.infer<typeof StashShowParamsSchema>;

export type StashPushParams = z.infer<typeof StashPushParamsSchema>;

export type StashPopParams = z.infer<typeof StashPopParamsSchema>;

export type StashApplyParams = z.infer<typeof StashApplyParamsSchema>;

export type StashDropParams = z.infer<typeof StashDropParamsSchema>;

export type StashBranchParams = z.infer<typeof StashBranchParamsSchema>;

export type StashRestoreFileParams = z.infer<typeof StashRestoreFileParamsSchema>;

export type GetPatchByFilePathParams = z.infer<typeof GetPatchByFilePathParamsSchema>;

export type CheckForUpdateByChannelParams = z.infer<typeof CheckForUpdateByChannelParamsSchema>;

export type DownloadAndInstallUpdateByChannelParams = z.infer<typeof DownloadAndInstallUpdateByChannelParamsSchema>;

export type GitAddParams = z.infer<typeof GitAddParamsSchema>;

export type GitRemoveParams = z.infer<typeof GitRemoveParamsSchema>;

export type GitDiscardParams = z.infer<typeof GitDiscardParamsSchema>;

export type GitApplyPatchBlockParams = z.infer<typeof GitApplyPatchBlockParamsSchema>;

export type AddLocalGitRepoParams = z.infer<typeof AddLocalGitRepoParamsSchema>;

export type CloneRepositoryParams = z.infer<typeof CloneRepositoryParamsSchema>;

export type InitRepositoryParams = z.infer<typeof InitRepositoryParamsSchema>;

export type CancelCloneRepositoryParams = z.infer<typeof CancelCloneRepositoryParamsSchema>;

export type SelectRepositoryParams = z.infer<typeof SelectRepositoryParamsSchema>;

export type OpenWithAppParams = z.infer<typeof OpenWithAppParamsSchema>;

export type ListRepositoriesParams = z.infer<typeof ListRepositoriesParamsSchema>;

export type AddRepositoryParams = z.infer<typeof AddRepositoryParamsSchema>;

export type RemoveRepositoryParams = z.infer<typeof RemoveRepositoryParamsSchema>;

export type RefreshRepositoryInfoParams = z.infer<typeof RefreshRepositoryInfoParamsSchema>;

export type ListBranchesParams = z.infer<typeof ListBranchesParamsSchema>;

export type GetBranchInfoParams = z.infer<typeof GetBranchInfoParamsSchema>;

export type SwitchBranchParams = z.infer<typeof SwitchBranchParamsSchema>;

export type CreateBranchParams = z.infer<typeof CreateBranchParamsSchema>;

export type CommitByIdParams = z.infer<typeof CommitByIdParamsSchema>;

export type CreateCommitParams = z.infer<typeof CreateCommitParamsSchema>;

