/**
 * Auto-generated TypeScript types for Tauri commands
 * Generated by tauri-typegen v0.3.2
 * Generated at: 2026-02-16T09:25:36Z
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';


export const SwimlaneSchema = z.object({
  id: z.string(),
  color: z.number(),
  is_stash: z.boolean(),
});

export const FileDiffSchema = z.object({
  old_path: z.string().optional(),
  new_path: z.string().optional(),
  status: z.string(),
  patch: z.string(),
});

export const AuthorSchema = z.object({
  name: z.string(),
  email: z.string(),
});

export const CommitAuthorsSchema = z.object({
  author: AuthorSchema,
  committer: AuthorSchema,
  co_authors: z.array(AuthorSchema),
});

export const CommitInfoSchema = z.object({
  id: z.string(),
  summary: z.string(),
  body: z.string(),
  timestamp: z.number(),
  authors: CommitAuthorsSchema,
});

export const BranchKindSchema = z.enum(["Local", "Remote"]);

export const RepositoryInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  origin: z.string().optional(),
  current_branch: z.string().optional(),
  ahead_behind: z.tuple([z.number(), z.number()]).optional(),
  has_uncommitted_changes: z.boolean(),
  last_updated: z.number(),
});

export const BranchSchema = z.object({
  name: z.string(),
  display_name: z.string(),
  is_remote: z.boolean(),
});

export const CommitStatsSchema = z.object({
  insertions: z.number(),
  deletions: z.number(),
  files_changed: z.number(),
});

export const FullCommitInfoSchema = z.object({
  id: z.string(),
  timestamp: z.number(),
  summary: z.string(),
  body: z.string(),
  authors: CommitAuthorsSchema,
  stats: CommitStatsSchema,
});

export const CommitMessageSchema = z.object({
  title: z.string(),
  description: z.string().optional(),
  co_authors: z.array(z.tuple([z.string(), z.string()])),
});

export const FileStatusKindSchema = z.enum(["IndexNew", "IndexModified", "IndexDeleted", "IndexRenamed", "IndexTypechange", "WorktreeNew", "WorktreeModified", "WorktreeDeleted", "WorktreeRenamed", "WorktreeTypechange", "WorktreeUnreadable", "Conflicted"]);

export const GraphRowTypeSchema = z.enum(["Commit", "Stash"]);

export const ParentEdgeSchema = z.object({
  oid: z.string(),
  lane: z.number(),
});

export const GraphRefSchema = z.object({
  name: z.string(),
  kind: z.string(),
  is_head: z.boolean(),
});

export const GraphRowSchema = z.object({
  oid: z.string(),
  lane: z.number(),
  commit: FullCommitInfoSchema,
  parents: z.array(ParentEdgeSchema),
  type: GraphRowTypeSchema,
  refs: z.array(GraphRefSchema),
  heads: z.array(GraphRefSchema),
  remotes: z.array(GraphRefSchema),
  tags: z.array(GraphRefSchema),
  stashes: z.array(GraphRefSchema),
  input_swimlanes: z.array(SwimlaneSchema),
  output_swimlanes: z.array(SwimlaneSchema),
});

export const RepoSitoryStoreSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  origin: z.string().optional(),
  current_branch: z.string().optional(),
  ahead_behind: z.tuple([z.number(), z.number()]).optional(),
  has_uncommitted_changes: z.boolean(),
  last_updated: z.number(),
});

export const AheadBehindStatusSchema = z.object({
  ahead: z.number(),
  behind: z.number(),
  local_branch: z.string(),
  local_branch_id: z.string(),
  upstream_branch: z.string().optional(),
  upstream_branch_id: z.string().optional(),
  is_published: z.boolean(),
});

export const RepositoryOriginSchema = z.object({
  remote_name: z.string(),
  remote_url: z.string(),
  host: z.string().optional(),
  provider: z.string().optional(),
  owner: z.string().optional(),
  repo: z.string().optional(),
  protocol: z.string(),
});

export const UncommittedChangesStrategySchema = z.enum(["StashOnCurrentBranch", "BringChanges"]);

export const HistoryQuerySchema = z.object({
  cursor: z.string().optional(),
  limit: z.number(),
  search: z.string().optional(),
  branch: z.string().optional(),
  graph_state: z.string().optional(),
  include_local: z.boolean(),
  include_remotes: z.boolean(),
  include_tags: z.boolean(),
  include_stash: z.boolean(),
});

export const FileStatusSchema = z.object({
  path: z.string(),
  new_path: z.string().optional(),
  status: z.array(FileStatusKindSchema),
});

export const GetStatusResponseSchema = z.object({
  files: z.array(FileStatusSchema),
});

export const GraphPagingSchema = z.object({
  starting_cursor: z.string().optional(),
  has_more: z.boolean(),
});

export const BranchInfoSchema = z.object({
  name: z.string(),
  display_name: z.string(),
  is_remote: z.boolean(),
  is_head: z.boolean(),
  commit: CommitInfoSchema,
  upstream: z.string().optional(),
  ahead: z.number().optional(),
  behind: z.number().optional(),
});

export const HistoryGraphResponseSchema = z.object({
  rows: z.array(GraphRowSchema),
  cursor: z.string().optional(),
  graph_state: z.string().optional(),
  has_more: z.boolean(),
  paging: GraphPagingSchema,
});

export const ListRepositoriesParamsSchema = z.object({
  refreshStale: z.boolean().optional(),
});

export const AddRepositoryParamsSchema = z.object({
  repo: RepositoryInfoSchema,
});

export const RemoveRepositoryParamsSchema = z.object({
  repoId: z.string(),
});

export const RefreshRepositoryInfoParamsSchema = z.object({
  repoId: z.string(),
});

export const HistoryParamsSchema = z.object({
  skip: z.number(),
  limit: z.number(),
});

export const HistoryGraphParamsSchema = z.object({
  query: HistoryQuerySchema,
});

export const GetPatchByFilePathParamsSchema = z.object({
  filePath: z.string(),
});

export const GetDiffParamsSchema = z.object({
  repoPath: z.string(),
  filePath: z.string(),
  target: z.string(),
  commitId: z.string().optional(),
});

export const CommitByIdParamsSchema = z.object({
  hash: z.string(),
});

export const CreateCommitParamsSchema = z.object({
  commitMeta: CommitMessageSchema,
  allowEmpty: z.boolean(),
});

export const AddLocalGitRepoParamsSchema = z.object({
  repoPath: z.string(),
});

export const SelectRepositoryParamsSchema = z.object({
  repoId: z.string(),
});

export const GitAddParamsSchema = z.object({
  file: z.string(),
});

export const GitRemoveParamsSchema = z.object({
  file: z.string(),
});

export const GitDiscardParamsSchema = z.object({
  file: z.string(),
  all: z.boolean().optional(),
});

export const ListBranchesParamsSchema = z.object({
  kind: BranchKindSchema,
});

export const GetBranchInfoParamsSchema = z.object({
  branchName: z.string(),
});

export const SwitchBranchParamsSchema = z.object({
  branch: z.string(),
  strategy: UncommittedChangesStrategySchema.optional(),
});

export const CreateBranchParamsSchema = z.object({
  branch: z.string(),
  strategy: UncommittedChangesStrategySchema.optional(),
});

export type ListRepositoriesParams = z.infer<typeof ListRepositoriesParamsSchema>;

export type AddRepositoryParams = z.infer<typeof AddRepositoryParamsSchema>;

export type RemoveRepositoryParams = z.infer<typeof RemoveRepositoryParamsSchema>;

export type RefreshRepositoryInfoParams = z.infer<typeof RefreshRepositoryInfoParamsSchema>;

export type HistoryParams = z.infer<typeof HistoryParamsSchema>;

export type HistoryGraphParams = z.infer<typeof HistoryGraphParamsSchema>;

export type GetPatchByFilePathParams = z.infer<typeof GetPatchByFilePathParamsSchema>;

export type GetDiffParams = z.infer<typeof GetDiffParamsSchema>;

export type CommitByIdParams = z.infer<typeof CommitByIdParamsSchema>;

export type CreateCommitParams = z.infer<typeof CreateCommitParamsSchema>;

export type AddLocalGitRepoParams = z.infer<typeof AddLocalGitRepoParamsSchema>;

export type SelectRepositoryParams = z.infer<typeof SelectRepositoryParamsSchema>;

export type GitAddParams = z.infer<typeof GitAddParamsSchema>;

export type GitRemoveParams = z.infer<typeof GitRemoveParamsSchema>;

export type GitDiscardParams = z.infer<typeof GitDiscardParamsSchema>;

export type ListBranchesParams = z.infer<typeof ListBranchesParamsSchema>;

export type GetBranchInfoParams = z.infer<typeof GetBranchInfoParamsSchema>;

export type SwitchBranchParams = z.infer<typeof SwitchBranchParamsSchema>;

export type CreateBranchParams = z.infer<typeof CreateBranchParamsSchema>;

export type HistoryQuery = z.infer<typeof HistoryQuerySchema>;

export type FileDiff = z.infer<typeof FileDiffSchema>;

export type ParentEdge = z.infer<typeof ParentEdgeSchema>;

export type BranchKind = z.infer<typeof BranchKindSchema>;

export type RepositoryInfo = z.infer<typeof RepositoryInfoSchema>;

export type FileStatus = z.infer<typeof FileStatusSchema>;

export type GraphRow = z.infer<typeof GraphRowSchema>;

export type GraphRef = z.infer<typeof GraphRefSchema>;

export type Author = z.infer<typeof AuthorSchema>;

export type RepositoryOrigin = z.infer<typeof RepositoryOriginSchema>;

export type CommitMessage = z.infer<typeof CommitMessageSchema>;

export type CommitInfo = z.infer<typeof CommitInfoSchema>;

export type RepoSitoryStore = z.infer<typeof RepoSitoryStoreSchema>;

export type UncommittedChangesStrategy = z.infer<typeof UncommittedChangesStrategySchema>;

export type CommitAuthors = z.infer<typeof CommitAuthorsSchema>;

export type Branch = z.infer<typeof BranchSchema>;

export type BranchInfo = z.infer<typeof BranchInfoSchema>;

export type GetStatusResponse = z.infer<typeof GetStatusResponseSchema>;

export type FileStatusKind = z.infer<typeof FileStatusKindSchema>;

export type GraphPaging = z.infer<typeof GraphPagingSchema>;

export type Swimlane = z.infer<typeof SwimlaneSchema>;

export type AheadBehindStatus = z.infer<typeof AheadBehindStatusSchema>;

export type GraphRowType = z.infer<typeof GraphRowTypeSchema>;

export type HistoryGraphResponse = z.infer<typeof HistoryGraphResponseSchema>;

export type CommitStats = z.infer<typeof CommitStatsSchema>;

export type FullCommitInfo = z.infer<typeof FullCommitInfoSchema>;

