name: release-please-stable

on:
  push:
    branches:
      - stable

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RURU_PAT_GH }}
          config-file: .release-please-stable.json
          manifest-file: .release-please-manifest.json
          target-branch: stable
